/**
 * InternAtlas - Target Company Master Catalog
 * Full categorization of Tech Giants, Quant/HFT, Indian Unicorns, AI & Analytics, and Enterprise IT.
 * Provides ATS configurations (Greenhouse, Lever, Ashby, Workday, SmartRecruiters, REST/GraphQL)
 * for real-time live web scraping, deterministic deduplication, and 2-Layer RAG matching.
 */

export type CompanyCategory =
  | 'Tech Giants & Big Tech'
  | 'Finance & Quant/HFT'
  | 'High-Growth / Indian Tech Unicorns'
  | 'AI & Analytics'
  | 'Enterprise Services & IT';

export type AtsProviderType =
  | 'greenhouse'
  | 'lever'
  | 'ashby'
  | 'workday'
  | 'smartrecruiters'
  | 'custom_rest';

export interface TargetCompanyMetadata {
  id: string;
  name: string;
  category: CompanyCategory;
  tier: string;
  atsProvider: AtsProviderType;
  boardToken: string; // token used in Greenhouse / Lever / Ashby endpoints
  careersUrl: string;
  primaryLocations: string[];
  sampleRoles: string[];
  typicalHiringBar: 'Extreme' | 'Hard' | 'Medium' | 'Foundational';
  dsaFocus: string[];
  compensationRange: string;
  internshipSeasons: string[];
  isRealtimeEnabled: boolean;
}

export const TARGET_COMPANIES_CATALOG: TargetCompanyMetadata[] = [
  // ==========================================
  // 1. TECH GIANTS & BIG TECH (23 Companies)
  // ==========================================
  {
    id: 'comp-google',
    name: 'Google',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'custom_rest',
    boardToken: 'google',
    careersUrl: 'https://careers.google.com/jobs/results/?q=intern',
    primaryLocations: ['Mountain View, CA', 'Sunnyvale, CA', 'New York, NY', 'Seattle, WA', 'Bangalore, India', 'Hyderabad, India', 'Remote'],
    sampleRoles: ['Software Engineering Intern (STEP & SWE)', 'Hardware Engineering Intern', 'AI/ML Research Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Graph Algorithms', 'Dynamic Programming', 'Trie / Segment Trees', 'Code Quality & Modularity'],
    compensationRange: '$58 - $68/hr ($10,000/mo) + Housing Stipend',
    internshipSeasons: ['Summer 2026', 'Fall 2026', 'Winter 2027'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-microsoft',
    name: 'Microsoft',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'lever',
    boardToken: 'microsoft',
    careersUrl: 'https://careers.microsoft.com/students/us/en',
    primaryLocations: ['Redmond, WA', 'Sunnyvale, CA', 'Atlanta, GA', 'Bangalore, India', 'Hyderabad, India', 'Noida, India'],
    sampleRoles: ['Software Engineering Intern', 'Explore Intern (Freshmen/Sophomores)', 'AI Cloud Platform Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Trees & BST', 'Two Pointers & Sliding Window', 'HashMaps', 'System Architecture Fundamentals'],
    compensationRange: '$50 - $60/hr ($9,000/mo) + Full Relocation & Corporate Housing',
    internshipSeasons: ['Summer 2026', 'Fall 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-amazon',
    name: 'Amazon',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'custom_rest',
    boardToken: 'amazon',
    careersUrl: 'https://amazon.jobs/en/business_categories/student-programs',
    primaryLocations: ['Seattle, WA', 'Arlington, VA', 'Austin, TX', 'Sunnyvale, CA', 'Bangalore, India', 'Hyderabad, India', 'Chennai, India'],
    sampleRoles: ['Software Development Engineer (SDE) Intern', 'AWS Systems Intern', 'Data Science Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Trees & Graphs (BFS/DFS)', 'Priority Queues / Heaps', '14 Leadership Principles Behavioral', 'Object Oriented Design'],
    compensationRange: '$55 - $64/hr + $2,500/mo Housing Stipend',
    internshipSeasons: ['Summer 2026', 'Fall 2026', 'Winter 2027'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-meta',
    name: 'Meta',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'custom_rest',
    boardToken: 'meta',
    careersUrl: 'https://www.metacareers.com/students-and-grads/',
    primaryLocations: ['Menlo Park, CA', 'Seattle, WA', 'New York, NY', 'London, UK', 'Remote (US)'],
    sampleRoles: ['Software Engineering Intern', 'Meta University (Freshmen/Sophomore)', 'AI Infra & PyTorch Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['LeetCode Meta Top 100', 'Fast Coding Speed & Accuracy', 'Dynamic Programming', 'Graph Shortest Paths'],
    compensationRange: '$60 - $72/hr ($10,500/mo) + Luxury Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-apple',
    name: 'Apple',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'custom_rest',
    boardToken: 'apple',
    careersUrl: 'https://jobs.apple.com/en-us/search?search=intern',
    primaryLocations: ['Cupertino, CA', 'Austin, TX', 'Seattle, WA', 'San Diego, CA', 'Bangalore, India', 'Hyderabad, India'],
    sampleRoles: ['Software Engineering Intern (CoreOS / iOS)', 'Silicon Design & Verification Intern', 'Machine Learning & AI Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['C/C++ Memory Management', 'Operating System Fundamentals', 'Data Structures & Pointer Manipulation'],
    compensationRange: '$52 - $65/hr + Corporate Housing',
    internshipSeasons: ['Summer 2026', 'Year-round Co-op'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-nvidia',
    name: 'NVIDIA',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 AI Labs',
    atsProvider: 'greenhouse',
    boardToken: 'nvidia',
    careersUrl: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite',
    primaryLocations: ['Santa Clara, CA', 'Austin, TX', 'Redmond, WA', 'Bangalore, India', 'Pune, India', 'Remote'],
    sampleRoles: ['CUDA & GPU Architecture Intern', 'Deep Learning Software Intern', 'Autonomous Vehicles AI Intern'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['CUDA Kernel Programming', 'Low-Level C++', 'Memory Bandwidth Optimization', 'Matrix Multiplications (GEMM)'],
    compensationRange: '$58 - $72/hr ($10,000/mo) + $3,000/mo Relocation',
    internshipSeasons: ['Summer 2026', 'Fall 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-adobe',
    name: 'Adobe',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'adobe',
    careersUrl: 'https://careers.adobe.com/us/en/university-recruiting',
    primaryLocations: ['San Jose, CA', 'San Francisco, CA', 'Seattle, WA', 'Noida, India', 'Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern', 'Creative Cloud WebAssembly Intern', 'Applied Research Intern (Firefly)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Algorithms & Data Structures', 'C++/JavaScript Rendering Engines', 'REST API Architecture'],
    compensationRange: '$48 - $58/hr + Housing Allowance',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-atlassian',
    name: 'Atlassian',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'lever',
    boardToken: 'atlassian',
    careersUrl: 'https://www.atlassian.com/company/careers/students',
    primaryLocations: ['San Francisco, CA', 'Mountain View, CA', 'Sydney, Australia', 'Bangalore, India', 'Remote (TEAM Anywhere)'],
    sampleRoles: ['Software Engineer Intern (Cloud & Jira)', 'Site Reliability Engineering Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['System Design Basics', 'Clean Java / TypeScript Coding', 'Concurrency & REST APIs'],
    compensationRange: '$52 - $60/hr + Full Remote Work Stipend',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-uber',
    name: 'Uber',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'greenhouse',
    boardToken: 'uber',
    careersUrl: 'https://www.uber.com/us/en/careers/teams/university/',
    primaryLocations: ['San Francisco, CA', 'Sunnyvale, CA', 'Seattle, WA', 'Bangalore, India', 'Hyderabad, India'],
    sampleRoles: ['Software Engineering Intern (Distributed Systems & Marketplace)', 'Data Science Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Graph Shortest Path & Routing', 'Distributed Systems (Go/Java)', 'Concurrency & Caching (Redis)'],
    compensationRange: '$58 - $68/hr + Corporate Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-linkedin',
    name: 'LinkedIn',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'custom_rest',
    boardToken: 'linkedin',
    careersUrl: 'https://careers.linkedin.com/students',
    primaryLocations: ['Sunnyvale, CA', 'Mountain View, CA', 'San Francisco, CA', 'Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Kafka & Graph Ingestion)', 'AI/ML Infrastructure Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Graph Algorithms', 'Kafka Stream Processing', 'Distributed Cache Consistency', 'Java / Python'],
    compensationRange: '$56 - $65/hr + $2,800/mo Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-salesforce',
    name: 'Salesforce',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'salesforce',
    careersUrl: 'https://www.salesforce.com/company/careers/university-recruiting/',
    primaryLocations: ['San Francisco, CA', 'Seattle, WA', 'Atlanta, GA', 'Hyderabad, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern (Core Platform)', 'Einstein AI Intern', 'Cloud Infrastructure Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Python Object-Oriented Design', 'Relational DB Optimization', 'REST APIs'],
    compensationRange: '$50 - $60/hr + Housing Stipend',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-servicenow',
    name: 'ServiceNow',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'smartrecruiters',
    boardToken: 'servicenow',
    careersUrl: 'https://careers.servicenow.com/early-career',
    primaryLocations: ['Santa Clara, CA', 'San Diego, CA', 'Hyderabad, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern', 'Cloud Platform Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Data Structures & Algorithms', 'JavaScript / Java Full Stack', 'Relational Schemas'],
    compensationRange: '$48 - $58/hr + Relocation Bonus',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-walmart',
    name: 'Walmart Global Tech',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'walmart',
    careersUrl: 'https://careers.walmart.com/technology/students',
    primaryLocations: ['Sunnyvale, CA', 'Bentonville, AR', 'Hoboken, NJ', 'Bangalore, India', 'Chennai, India'],
    sampleRoles: ['Software Development Engineer Intern', 'Data Science & Supply Chain Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Arrays & Strings', 'Trees & BFS/DFS', 'Java / Spring Microservices'],
    compensationRange: '$45 - $55/hr + Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-intuit',
    name: 'Intuit',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'intuit',
    careersUrl: 'https://www.intuit.com/careers/university-recruiting/',
    primaryLocations: ['Mountain View, CA', 'San Diego, CA', 'Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (TurboTax & QuickBooks Engine)', 'AI Financial Analytics Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Object Oriented Design', 'Algorithm Efficiency', 'React / Java APIs'],
    compensationRange: '$50 - $60/hr + Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-oracle',
    name: 'Oracle',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'custom_rest',
    boardToken: 'oracle',
    careersUrl: 'https://www.oracle.com/corporate/careers/students-grads/',
    primaryLocations: ['Austin, TX', 'Redwood City, CA', 'Seattle, WA', 'Bangalore, India', 'Hyderabad, India', 'Noida, India'],
    sampleRoles: ['Software Developer Intern (Oracle Cloud Infrastructure / OCI)', 'Database Kernel Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Distributed Systems', 'C/C++ Concurrency', 'Network Protocols & Storage Architecture'],
    compensationRange: '$48 - $58/hr + Relocation',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-sap',
    name: 'SAP',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'custom_rest',
    boardToken: 'sap',
    careersUrl: 'https://jobs.sap.com/content/Students-and-Graduates/',
    primaryLocations: ['Palo Alto, CA', 'Walldorf, Germany', 'Bangalore, India', 'Gurgaon, India'],
    sampleRoles: ['Software Development Intern (HANA In-Memory Database)', 'Cloud Infrastructure Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['C++ / Java Memory Layouts', 'Database Query Optimization', 'REST Microservices'],
    compensationRange: '$40 - $50/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-cisco',
    name: 'Cisco',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'cisco',
    careersUrl: 'https://jobs.cisco.com/jobs/SearchJobs/intern',
    primaryLocations: ['San Jose, CA', 'RTP, NC', 'Bangalore, India', 'Chennai, India'],
    sampleRoles: ['Software Engineer Intern (Networking Protocols & Security)', 'Cloud DevOps Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['TCP/IP Network Stack', 'C/C++ Pointer Mechanics', 'Socket Programming'],
    compensationRange: '$45 - $55/hr + Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-qualcomm',
    name: 'Qualcomm',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'qualcomm',
    careersUrl: 'https://qualcomm.wd5.myworkdayjobs.com/External',
    primaryLocations: ['San Diego, CA', 'Santa Clara, CA', 'Hyderabad, India', 'Bangalore, India', 'Chennai, India'],
    sampleRoles: ['Software Engineering Intern (Snapdragon NPU / 5G DSP)', 'Embedded Systems Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Embedded C/C++', 'Bit Manipulation', 'Operating Systems & Thread Synchronization'],
    compensationRange: '$46 - $56/hr + Corporate Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-intel',
    name: 'Intel',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'intel',
    careersUrl: 'https://jobs.intel.com/en/student-center',
    primaryLocations: ['Santa Clara, CA', 'Hillsboro, OR', 'Austin, TX', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern (Compilers & AI Drivers)', 'Silicon Architecture Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['C/C++ LLVM Compilers', 'Hardware Vector SIMD Extensions', 'Linux Kernel Internals'],
    compensationRange: '$44 - $54/hr + Housing Stipend',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-amd',
    name: 'AMD',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'greenhouse',
    boardToken: 'amd',
    careersUrl: 'https://careers.amd.com/students',
    primaryLocations: ['Santa Clara, CA', 'Austin, TX', 'Bangalore, India', 'Hyderabad, India'],
    sampleRoles: ['Software Development Intern (ROCm GPU Compute)', 'Firmware & BIOS Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['C++ ROCm / HIP GPU Programming', 'Compilers & Concurrency', 'Data Structures'],
    compensationRange: '$46 - $56/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-ti',
    name: 'Texas Instruments',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'ti',
    careersUrl: 'https://careers.ti.com/students/',
    primaryLocations: ['Dallas, TX', 'Bangalore, India'],
    sampleRoles: ['Embedded Software Engineering Intern', 'Digital Signal Processing Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Embedded C', 'Microcontrollers & RTOS', 'Algorithms & Data Structures'],
    compensationRange: '$40 - $48/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-broadcom',
    name: 'Broadcom',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'broadcom',
    careersUrl: 'https://broadcom.wd1.myworkdayjobs.com/External_Career',
    primaryLocations: ['San Jose, CA', 'Irvine, CA', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern (ASIC Drivers & Networking)', 'Firmware Engineer Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['C/C++ Network Protocols', 'Hardware Device Drivers', 'Low-level Memory Access'],
    compensationRange: '$46 - $55/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-vmware',
    name: 'VMware',
    category: 'Tech Giants & Big Tech',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'vmware',
    careersUrl: 'https://careers.vmware.com/students',
    primaryLocations: ['Palo Alto, CA', 'Bangalore, India', 'Remote'],
    sampleRoles: ['Software Engineer Intern (Virtualization & Hypervisors)', 'Cloud Systems Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Hypervisor C/C++', 'Distributed Storage & K8s', 'Linux Kernel Subsystems'],
    compensationRange: '$48 - $58/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },

  // ==========================================
  // 2. FINANCE & QUANT/HFT (16 Companies)
  // ==========================================
  {
    id: 'comp-jpmorgan',
    name: 'JPMorgan Chase',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'custom_rest',
    boardToken: 'jpmorganchase',
    careersUrl: 'https://careers.jpmorgan.com/us/en/students/programs',
    primaryLocations: ['New York, NY', 'Plano, TX', 'Chicago, IL', 'London, UK', 'Mumbai, India', 'Bangalore, India', 'Hyderabad, India'],
    sampleRoles: ['Software Engineer Program (SEP) Summer Analyst', 'Quantitative Research Analyst Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Spring Boot APIs', 'SQL Database Normalization', 'Medium LeetCode Algorithms'],
    compensationRange: '$50.00/hr ($8,000/mo) + Relocation',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-goldman',
    name: 'Goldman Sachs',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'greenhouse',
    boardToken: 'goldmansachs',
    careersUrl: 'https://www.goldmansachs.com/careers/students/programs/',
    primaryLocations: ['New York, NY', 'Dallas, TX', 'Salt Lake City, UT', 'Bangalore, India', 'Hyderabad, India'],
    sampleRoles: ['Summer Analyst - Engineering & Quant Strategy', 'Global Markets Tech Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Dynamic Programming (Knapsack & Grid DP)', 'Graph Shortest Paths', 'Object Oriented C++/Java Design'],
    compensationRange: '$52.88/hr (~$8,500/mo) + $2,500 Relocation',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-deshaw-fin',
    name: 'DE Shaw',
    category: 'Finance & Quant/HFT',
    tier: 'Tier 1 Quant/HFT',
    atsProvider: 'greenhouse',
    boardToken: 'deshaw',
    careersUrl: 'https://www.deshaw.com/careers/internships',
    primaryLocations: ['New York, NY', 'Hyderabad, India', 'London, UK'],
    sampleRoles: ['Software Development Intern', 'Quantitative Analyst Intern'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Hard Dynamic Programming', 'Graph Theory & Network Flow', 'Algorithmic Optimization & C++'],
    compensationRange: '$110.00/hr (~$17,500/mo) + Luxury Manhattan Apartment',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-janestreet',
    name: 'Jane Street',
    category: 'Finance & Quant/HFT',
    tier: 'Tier 1 Quant/HFT',
    atsProvider: 'ashby',
    boardToken: 'janestreet',
    careersUrl: 'https://www.janestreet.com/join-jane-street/students-and-grads/',
    primaryLocations: ['New York, NY', 'London, UK', 'Hong Kong', 'Singapore'],
    sampleRoles: ['Software Engineering Intern (OCaml & High-Performance Systems)', 'Quantitative Trading Intern'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['OCaml Functional Programming', 'State Machine Invariants', 'Type Systems & Deterministic Concurrency'],
    compensationRange: '$125.00/hr (~$20,000/mo) + Luxury Corporate Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-citadel-sec',
    name: 'Citadel',
    category: 'Finance & Quant/HFT',
    tier: 'Tier 1 Quant/HFT',
    atsProvider: 'greenhouse',
    boardToken: 'citadel',
    careersUrl: 'https://www.citadelsecurities.com/careers/students/',
    primaryLocations: ['New York, NY', 'Chicago, IL', 'Miami, FL', 'London, UK', 'Hong Kong'],
    sampleRoles: ['Software Engineering Intern (Low Latency C++ Platform)', 'Quantitative Research Intern'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Microsecond C++20', 'Lock-Free Queues & Atomic Variables', 'CPU Cache Optimization & SIMD', 'Codeforces 1900+ DP'],
    compensationRange: '$120 - $145/hr ($5,000/wk) + $10,000 Sign-on & Luxury Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-tower-res',
    name: 'Tower Research',
    category: 'Finance & Quant/HFT',
    tier: 'Tier 1 Quant/HFT',
    atsProvider: 'greenhouse',
    boardToken: 'tower-research-capital',
    careersUrl: 'https://www.tower-research.com/open-positions',
    primaryLocations: ['New York, NY', 'Chicago, IL', 'Gurgaon, India'],
    sampleRoles: ['Quantitative Trading Intern', 'Core Engineering & Low Latency C++ Intern'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Modern C++20 Templates', 'Linux Kernel Network Bypass (Solarflare)', 'Extreme Algorithmic Rigor'],
    compensationRange: '$115 - $135/hr + Full Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-paypal',
    name: 'PayPal',
    category: 'Finance & Quant/HFT',
    tier: 'Tier 1 Big Tech (FAANG+)',
    atsProvider: 'workday',
    boardToken: 'paypal',
    careersUrl: 'https://careers.pypl.com/university/',
    primaryLocations: ['San Jose, CA', 'Scottsdale, AZ', 'Chennai, India', 'Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (Checkout & Risk Infrastructure)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Node.js API Resilience', 'Idempotent Payment Workflows', 'SQL / NoSQL Datastores'],
    compensationRange: '$48 - $58/hr + Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-visa',
    name: 'Visa',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'smartrecruiters',
    boardToken: 'visa',
    careersUrl: 'https://corporate.visa.com/en/careers/students-and-graduates.html',
    primaryLocations: ['Foster City, CA', 'Austin, TX', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern (VisaNet Transaction Switch)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / C++ Concurrency', 'Distributed Transaction Processing', 'Security & Cryptography'],
    compensationRange: '$48 - $58/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-mastercard',
    name: 'Mastercard',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'workday',
    boardToken: 'mastercard',
    careersUrl: 'https://careers.mastercard.com/us/en/students-graduates',
    primaryLocations: ['New York, NY', 'O\'Fallon, MO', 'Pune, India', 'Gurgaon, India'],
    sampleRoles: ['Software Engineering Summer Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Object Oriented Programming', 'Spring Cloud & REST', 'Algorithms'],
    compensationRange: '$46 - $54/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-amex',
    name: 'American Express',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'workday',
    boardToken: 'americanexpress',
    careersUrl: 'https://careers.americanexpress.com/Students',
    primaryLocations: ['New York, NY', 'Phoenix, AZ', 'Gurgaon, India', 'Bangalore, India'],
    sampleRoles: ['Technology Summer Intern (Card Engine & AI Fraud Detection)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Python Algorithms', 'Distributed Event Streaming (Kafka)', 'SQL Data Processing'],
    compensationRange: '$48 - $56/hr + Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-barclays',
    name: 'Barclays',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'workday',
    boardToken: 'barclays',
    careersUrl: 'https://search.jobs.barclays/students-and-graduates',
    primaryLocations: ['New York, NY', 'Whippany, NJ', 'London, UK', 'Pune, India'],
    sampleRoles: ['Technology Summer Analyst'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Algorithms & Data Structures', 'C++/Java Enterprise Patterns', 'SQL Queries'],
    compensationRange: '$45 - $52/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-morganstanley',
    name: 'Morgan Stanley',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'custom_rest',
    boardToken: 'morganstanley',
    careersUrl: 'https://www.morganstanley.com/people-opportunities/students-graduates',
    primaryLocations: ['New York, NY', 'Alpharetta, GA', 'Mumbai, India', 'Bangalore, India'],
    sampleRoles: ['Technology Summer Analyst (Fixed Income & Institutional Tech)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / C++ Algorithmic Efficiency', 'Relational Database Schema Design', 'OOP Concepts'],
    compensationRange: '$48 - $55/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-bofa',
    name: 'Bank of America',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'custom_rest',
    boardToken: 'bankofamerica',
    careersUrl: 'https://campus.bankofamerica.com/',
    primaryLocations: ['New York, NY', 'Charlotte, NC', 'Mumbai, India', 'Hyderabad, India'],
    sampleRoles: ['Global Technology Summer Analyst'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Data Structures', 'Python / Java / C# Development', 'Database Queries'],
    compensationRange: '$45 - $52/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-db',
    name: 'Deutsche Bank',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'custom_rest',
    boardToken: 'deutschebank',
    careersUrl: 'https://careers.db.com/students-graduates/',
    primaryLocations: ['New York, NY', 'Cary, NC', 'Pune, India', 'Bangalore, India'],
    sampleRoles: ['Technology Analyst Internship Program'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Algorithms & Data Structures', 'Java & Python', 'Relational DBs'],
    compensationRange: '$44 - $50/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-ubs',
    name: 'UBS',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'workday',
    boardToken: 'ubs',
    careersUrl: 'https://www.ubs.com/global/en/careers/students-and-graduates.html',
    primaryLocations: ['New York, NY', 'Weehawken, NJ', 'Zurich, Switzerland', 'Pune, India', 'Hyderabad, India'],
    sampleRoles: ['Technology Summer Internship Program'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Algorithms', 'Java / Python / Cloud Basics', 'SQL'],
    compensationRange: '$44 - $50/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-wellsfargo',
    name: 'Wells Fargo',
    category: 'Finance & Quant/HFT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'workday',
    boardToken: 'wellsfargo',
    careersUrl: 'https://www.wellsfargo.com/about/careers/early-careers/',
    primaryLocations: ['Charlotte, NC', 'San Francisco, CA', 'New York, NY', 'Hyderabad, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern (Digital Banking & Payments)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Spring Boot', 'Data Structures & Algorithms', 'REST APIs'],
    compensationRange: '$42 - $50/hr',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },

  // ==========================================
  // 3. HIGH-GROWTH / INDIAN TECH UNICORNS (35 Companies)
  // ==========================================
  {
    id: 'comp-flipkart',
    name: 'Flipkart',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'flipkart',
    careersUrl: 'https://www.flipkartcareers.com/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (SDE Intern)', 'Data Science Intern'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Hard Graphs & Dynamic Programming', 'High Scale Concurrency', 'Low-Level Machine Coding Round (2 hours)'],
    compensationRange: '₹1,00,000/mo ($1,200/mo) + Relocation & Stay',
    internshipSeasons: ['Summer 2026', '6-Month Spring 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-phonepe',
    name: 'PhonePe',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'phonepe',
    careersUrl: 'https://www.phonepe.com/careers/',
    primaryLocations: ['Bangalore, India', 'Pune, India'],
    sampleRoles: ['Software Engineer Intern (UPI Infrastructure & High Throughput)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['High-Concurrency Java / Aerospike', 'Data Structures & Dynamic Programming', 'Machine Coding Architecture'],
    compensationRange: '₹1,10,000/mo + Housing',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-razorpay',
    name: 'Razorpay',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'razorpay',
    careersUrl: 'https://razorpay.com/jobs/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Payments & Banking API Engine)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Golang / PHP Microservices', 'Idempotency & Distributed Locking', 'Algorithms & Code Quality'],
    compensationRange: '₹80,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-meesho',
    name: 'Meesho',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'meesho',
    careersUrl: 'https://www.meesho.io/jobs',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['SDE Intern - User Growth & Logistics Platform'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Java / Kotlin Microservices', 'Kafka Streams', 'DSA Graphs & Trees'],
    compensationRange: '₹85,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-swiggy',
    name: 'Swiggy',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'swiggy',
    careersUrl: 'https://careers.swiggy.com/',
    primaryLocations: ['Bangalore, India', 'Remote'],
    sampleRoles: ['Software Development Engineer Intern (Hyperlocal Delivery Engine)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Spatial Indexing (H3/QuadTree)', 'Dynamic Programming & Graph Routing', 'Golang / Java'],
    compensationRange: '₹90,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-zomato',
    name: 'Eternal / Zomato',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'zomato',
    careersUrl: 'https://www.zomato.com/careers',
    primaryLocations: ['Gurgaon, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern (Quick Commerce & Core App Engine)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Fast Iteration & Clean Code', 'Golang / Python / React Native', 'DSA Trees & Heaps'],
    compensationRange: '₹80,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-myntra',
    name: 'Myntra',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'myntra',
    careersUrl: 'https://careers.myntra.com/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (Fashion Discovery & Catalog)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Java / Spring Microservices', 'Data Structures & Algorithms', 'Machine Coding'],
    compensationRange: '₹80,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-cred',
    name: 'CRED',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'cred',
    careersUrl: 'https://careers.cred.club/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Frontend / Backend Core)'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Clean Code Architecture', 'Design Patterns & Extensibility', 'Hard Problem Solving'],
    compensationRange: '₹1,00,000 - ₹1,25,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-groww',
    name: 'Groww',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'groww',
    careersUrl: 'https://groww.in/careers',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (Stocks & Mutual Funds Platform)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['High-throughput Spring Boot', 'Microservices & Redis Caching', 'DSA Graphs & DP'],
    compensationRange: '₹80,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-zerodha',
    name: 'Zerodha',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'custom_rest',
    boardToken: 'zerodha',
    careersUrl: 'https://zerodha.com/careers',
    primaryLocations: ['Bangalore, India', 'Remote'],
    sampleRoles: ['Software Engineer Intern (Kite Trading Engine & Go Microservices)'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Golang / Python / PostgreSQL', 'Clean Code Minimalist Philosophy', 'Concurrency & Low Overhead'],
    compensationRange: '₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-paytm',
    name: 'Paytm',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'paytm',
    careersUrl: 'https://jobs.lever.co/paytm',
    primaryLocations: ['Noida, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Fintech & Cloud)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Node.js Microservices', 'Data Structures & Algorithms'],
    compensationRange: '₹50,000 - ₹70,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-dream11',
    name: 'Dream11',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'dream11',
    careersUrl: 'https://www.dream11.com/careers',
    primaryLocations: ['Mumbai, India'],
    sampleRoles: ['Software Development Engineer Intern (Hyper-Scale Sports Tech)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['High-Concurrency Leaderboard Systems', 'Java / Spark / Cassandra', 'Hard DP & Graph Theory'],
    compensationRange: '₹90,000/mo + Housing in Mumbai',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-makemytrip',
    name: 'MakeMyTrip',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'custom_rest',
    boardToken: 'makemytrip',
    careersUrl: 'https://careers.makemytrip.com/',
    primaryLocations: ['Gurgaon, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Flights & Hotels Search Engine)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Spring Microservices', 'Search Algorithms & Caching', 'DSA Trees & Graphs'],
    compensationRange: '₹60,000 - ₹75,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-nykaa',
    name: 'Nykaa',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'nykaa',
    careersUrl: 'https://www.nykaa.com/careers',
    primaryLocations: ['Mumbai, India', 'Gurgaon, India'],
    sampleRoles: ['Software Engineer Intern (Beauty Tech & Recommendation Systems)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Fullstack React / Java', 'Database Schemas', 'Algorithms'],
    compensationRange: '₹50,000 - ₹65,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-lenskart',
    name: 'Lenskart',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'lenskart',
    careersUrl: 'https://www.lenskart.com/careers',
    primaryLocations: ['Delhi NCR, India', 'Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (Omnichannel Systems)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / Python / Vue', 'Data Structures & Algorithms', 'REST APIs'],
    compensationRange: '₹50,000 - ₹65,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-zepto',
    name: 'Zepto',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'zepto',
    careersUrl: 'https://www.zeptonow.com/careers',
    primaryLocations: ['Bangalore, India', 'Mumbai, India'],
    sampleRoles: ['Software Engineering Intern (10-Minute Dark Store & Logistics Routing)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Golang / Python High Scale Microservices', 'Real-time Graph Routing', 'Dynamic Programming'],
    compensationRange: '₹90,000 - ₹1,10,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-blinkit',
    name: 'Blinkit',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'blinkit',
    careersUrl: 'https://blinkit.com/careers',
    primaryLocations: ['Gurgaon, India'],
    sampleRoles: ['Software Development Engineer Intern (Quick Commerce Supply Chain)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Golang / Java Microservices', 'Distributed Caching', 'DSA DP & Graphs'],
    compensationRange: '₹85,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-rapido',
    name: 'Rapido',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'rapido',
    careersUrl: 'https://www.rapido.bike/careers',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Bike-Taxi Match Engine & Spatial Tech)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Spatial Geohashing', 'Golang / Kafka Streams', 'Real-time Matchmaking Algorithms'],
    compensationRange: '₹75,000 - ₹90,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-delhivery',
    name: 'Delhivery',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'delhivery',
    careersUrl: 'https://www.delhivery.com/careers/',
    primaryLocations: ['Gurgaon, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Nationwide Logistics Network)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Python / Go / PostgreSQL', 'Traveling Salesperson / Routing Optimization', 'Algorithms'],
    compensationRange: '₹60,000 - ₹75,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-bigbasket',
    name: 'BigBasket',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'bigbasket',
    careersUrl: 'https://www.bigbasket.com/careers/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Warehouse Automation & Inventory)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Python / Django / Java', 'Database Query Optimization', 'Algorithms'],
    compensationRange: '₹55,000 - ₹70,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-postman',
    name: 'Postman',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'postman',
    careersUrl: 'https://www.postman.com/company/careers/',
    primaryLocations: ['Bangalore, India', 'San Francisco, CA', 'Remote'],
    sampleRoles: ['Software Engineering Intern (Developer Tools & API Platform)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Deep Node.js / Electron / Web Standards', 'HTTP/2, gRPC, WebSocket Protocols', 'Clean Code Quality'],
    compensationRange: '₹90,000 - ₹1,10,000/mo ($55/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-browserstack',
    name: 'BrowserStack',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'browserstack',
    careersUrl: 'https://www.browserstack.com/careers',
    primaryLocations: ['Mumbai, India', 'Dublin, Ireland', 'Remote'],
    sampleRoles: ['Software Engineer Intern (Cloud Device Virtualization & Infrastructure)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Linux Containers & Virtualization', 'Ruby / Go / Node.js Systems', 'Algorithms & Concurrency'],
    compensationRange: '₹80,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-freshworks',
    name: 'Freshworks',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'smartrecruiters',
    boardToken: 'freshworks',
    careersUrl: 'https://www.freshworks.com/company/careers/',
    primaryLocations: ['Chennai, India', 'San Mateo, CA'],
    sampleRoles: ['Software Engineering Intern (SaaS Multi-Tenant CRM Engine)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Ruby on Rails / Java', 'Relational Database Design & Indexing', 'DSA Arrays & Strings'],
    compensationRange: '₹60,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-zoho',
    name: 'Zoho',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'custom_rest',
    boardToken: 'zoho',
    careersUrl: 'https://www.zoho.com/careers/',
    primaryLocations: ['Chennai, India', 'Tenkasi, India', 'Austin, TX'],
    sampleRoles: ['Software Developer Intern (Zoho Creator / CRM / Suite)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Pure C & Java from Scratch', 'No External Frameworks Allowed', 'Memory Management & Custom Parsers'],
    compensationRange: '₹40,000 - ₹50,000/mo',
    internshipSeasons: ['Summer 2026', 'Year-Round'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-chargebee',
    name: 'Chargebee',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'chargebee',
    careersUrl: 'https://www.chargebee.com/careers/',
    primaryLocations: ['Chennai, India', 'Bangalore, India'],
    sampleRoles: ['Software Engineering Intern (Subscription Billing & Invoicing Engine)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / AWS Microservices', 'Transaction Integrity', 'Algorithms'],
    compensationRange: '₹55,000 - ₹70,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-inmobi',
    name: 'InMobi',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'inmobi',
    careersUrl: 'https://www.inmobi.com/company/careers/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (AdTech Real-Time Bidding Engine)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Sub-10ms Java Microservices', 'Distributed Kafka / Spark Stream Processing', 'DSA DP & Graphs'],
    compensationRange: '₹80,000 - ₹95,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-sharechat',
    name: 'ShareChat',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'sharechat',
    careersUrl: 'https://sharechat.com/careers',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Content Recommendation & Feeds)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Golang / Python Distributed Services', 'Graph Algorithms', 'Hard Dynamic Programming'],
    compensationRange: '₹85,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-juspay',
    name: 'Juspay',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'custom_rest',
    boardToken: 'juspay',
    careersUrl: 'https://juspay.in/careers',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (Functional Programming & Payment Switch)'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Haskell / PureScript Functional Programming', 'Hard Graph & Tree Algorithms (Juspay Hiring Challenge)', 'Type Safety'],
    compensationRange: '₹60,000 - ₹80,000/mo (Full-time: 27 LPA)',
    internshipSeasons: ['Summer 2026', '6-Month Winter/Spring'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-thoughtspot',
    name: 'ThoughtSpot',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'thoughtspot',
    careersUrl: 'https://www.thoughtspot.com/careers',
    primaryLocations: ['Bangalore, India', 'Sunnyvale, CA'],
    sampleRoles: ['Software Engineering Intern (Search-Driven AI Analytics Engine)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Modern C++ & Distributed Joins', 'Query Compilation', 'DSA Advanced DP & Segment Trees'],
    compensationRange: '₹1,00,000/mo ($60/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-amagi',
    name: 'Amagi',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'amagi',
    careersUrl: 'https://www.amagi.com/careers',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Engineer Intern (Cloud Broadcast & Video Streaming Tech)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['C++ / Go / Python Video Processing', 'HLS / WebRTC Protocols', 'Algorithms'],
    compensationRange: '₹60,000 - ₹75,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-druva',
    name: 'Druva',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'druva',
    careersUrl: 'https://www.druva.com/about/careers/',
    primaryLocations: ['Pune, India', 'Santa Clara, CA'],
    sampleRoles: ['Software Development Engineer Intern (Cloud Backup & Deduplication)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['C++ / Python Chunking Algorithms (Rabin Karp)', 'AWS S3 Storage Optimization', 'Algorithms'],
    compensationRange: '₹60,000 - ₹75,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-hasura',
    name: 'Hasura',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'hasura',
    careersUrl: 'https://hasura.io/careers/',
    primaryLocations: ['Bangalore, India', 'San Francisco, CA', 'Remote'],
    sampleRoles: ['Software Engineer Intern (GraphQL Engine & Compilers in Haskell/Rust)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Haskell / Rust Compilers', 'SQL AST Generation', 'Type Theory'],
    compensationRange: '₹80,000 - ₹1,00,000/mo ($50/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-moengage',
    name: 'MoEngage',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'moengage',
    careersUrl: 'https://www.moengage.com/careers/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Software Development Engineer Intern (Customer Engagement Platform)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Python / Java Microservices', 'Kafka Stream Processing', 'Data Structures'],
    compensationRange: '₹55,000 - ₹70,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-sarvamai',
    name: 'Sarvam AI',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'Tier 1 AI Labs',
    atsProvider: 'ashby',
    boardToken: 'sarvam-ai',
    careersUrl: 'https://www.sarvam.ai/careers',
    primaryLocations: ['Bangalore, India', 'Chennai, India'],
    sampleRoles: ['AI Research Intern (Indic LLMs, Voice Models, Speech Recognition)'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['PyTorch / JAX Distributed Training', 'Transformer Architecture & Quantization', 'Linear Algebra & NLP'],
    compensationRange: '₹1,00,000 - ₹1,50,000/mo',
    internshipSeasons: ['Summer 2026', 'Year-Round Research'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-krutrim',
    name: 'Krutrim',
    category: 'High-Growth / Indian Tech Unicorns',
    tier: 'Tier 1 AI Labs',
    atsProvider: 'lever',
    boardToken: 'krutrim-ai',
    careersUrl: 'https://ola.krutrim.com/careers',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['AI Systems & Silicon Intern (Silicon Design, Cloud AI GPUs)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['LLM Inference Optimization', 'C++ / CUDA / Triton', 'Deep Learning Architecture'],
    compensationRange: '₹80,000 - ₹1,00,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },

  // ==========================================
  // 4. AI & ANALYTICS (13 Companies)
  // ==========================================
  {
    id: 'comp-fractal',
    name: 'Fractal Analytics',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'fractalanalytics',
    careersUrl: 'https://fractal.ai/careers/',
    primaryLocations: ['New York, NY', 'Mumbai, India', 'Bangalore, India', 'Gurgaon, India'],
    sampleRoles: ['AI Engineering Intern', 'Data Science & Decision Analytics Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Python / PyTorch / Scikit-Learn', 'Statistical Inference & Hypothesis Testing', 'Algorithms'],
    compensationRange: '₹50,000 - ₹65,000/mo ($40/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-tigeranalytics',
    name: 'Tiger Analytics',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'tigeranalytics',
    careersUrl: 'https://www.tigeranalytics.com/careers/',
    primaryLocations: ['Chennai, India', 'Bangalore, India', 'Hyderabad, India', 'Jersey City, NJ'],
    sampleRoles: ['Data Science Intern (Predictive Analytics & ML Ops)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Python / SQL / Cloud ML', 'Regression & Tree Models', 'Data Structures'],
    compensationRange: '₹45,000 - ₹60,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-musigma',
    name: 'Mu Sigma',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'custom_rest',
    boardToken: 'musigma',
    careersUrl: 'https://www.mu-sigma.com/careers',
    primaryLocations: ['Bangalore, India', 'Chicago, IL'],
    sampleRoles: ['Decision Sciences Intern (Trainee Decision Scientist)'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Mu Sigma Aptitude Test (muApt)', 'Puzzles & Logical Reasoning', 'Python & SQL Basics'],
    compensationRange: '₹35,000 - ₹45,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-tredence',
    name: 'Tredence',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'tredence',
    careersUrl: 'https://www.tredence.com/careers',
    primaryLocations: ['Bangalore, India', 'San Jose, CA', 'Chicago, IL'],
    sampleRoles: ['Data Engineering Intern', 'AI Solution Developer Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['PySpark / Databricks', 'SQL Data Pipelines', 'Data Structures'],
    compensationRange: '₹45,000 - ₹60,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-latentview',
    name: 'LatentView Analytics',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'latentview',
    careersUrl: 'https://www.latentview.com/careers/',
    primaryLocations: ['Chennai, India', 'Bangalore, India', 'Princeton, NJ'],
    sampleRoles: ['Analytics Consultant Intern', 'Data Engineering Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Python / R / SQL', 'Business Analytics Modeling', 'Basic DSA'],
    compensationRange: '₹40,000 - ₹55,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-sigmoid',
    name: 'Sigmoid',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'sigmoid',
    careersUrl: 'https://www.sigmoid.com/careers/',
    primaryLocations: ['Bangalore, India', 'New York, NY'],
    sampleRoles: ['Data Engineering Intern (Spark & Cloud Data Warehousing)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Scala / Python / Apache Spark', 'Data Structures & Algorithms', 'SQL Optimization'],
    compensationRange: '₹50,000 - ₹65,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-uniphore',
    name: 'Uniphore',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'uniphore',
    careersUrl: 'https://www.uniphore.com/careers/',
    primaryLocations: ['Palo Alto, CA', 'Chennai, India', 'Bangalore, India'],
    sampleRoles: ['Conversational AI Intern (Speech & Natural Language)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['PyTorch / Transformers', 'Audio Processing (ASR/TTS)', 'DSA Problem Solving'],
    compensationRange: '₹60,000 - ₹80,000/mo ($45/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-yellowai',
    name: 'Yellow.ai',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'yellowai',
    careersUrl: 'https://yellow.ai/careers/',
    primaryLocations: ['Bangalore, India', 'San Mateo, CA'],
    sampleRoles: ['AI Platform Intern (DynamicNLP & Agentic Systems)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Node.js / Python Services', 'Vector Databases & LLM Orchestration', 'Algorithms'],
    compensationRange: '₹50,000 - ₹65,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-observeai',
    name: 'Observe.AI',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'greenhouse',
    boardToken: 'observeai',
    careersUrl: 'https://www.observe.ai/careers',
    primaryLocations: ['Bangalore, India', 'San Francisco, CA'],
    sampleRoles: ['Machine Learning Engineering Intern (LLM Contact Center Intelligence)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['NLP / LLM Fine-Tuning', 'Python / Distributed Microservices', 'Data Structures'],
    compensationRange: '₹70,000 - ₹85,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-aryaai',
    name: 'Arya.ai',
    category: 'AI & Analytics',
    tier: 'High-Growth Unicorn',
    atsProvider: 'lever',
    boardToken: 'arya-ai',
    careersUrl: 'https://arya.ai/careers',
    primaryLocations: ['Mumbai, India'],
    sampleRoles: ['Autonomous AI Intern (Deep Learning in BFSI)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Computer Vision / Document AI', 'PyTorch / Python', 'Algorithms'],
    compensationRange: '₹40,000 - ₹55,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-msr-india',
    name: 'Microsoft Research India',
    category: 'AI & Analytics',
    tier: 'Tier 1 AI Labs',
    atsProvider: 'custom_rest',
    boardToken: 'msr-india',
    careersUrl: 'https://www.microsoft.com/en-us/research/lab/microsoft-research-india/opportunities/',
    primaryLocations: ['Bangalore, India'],
    sampleRoles: ['Research Fellow Intern (Systems, Cryptography, AI & Societal Impact)'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Theoretical Computer Science', 'Rigorous Proofs & Complexity Theory', 'Advanced Machine Learning Papers'],
    compensationRange: '₹95,000/mo + Housing & Conference Travel Support',
    internshipSeasons: ['Summer 2026', '1-2 Year Fellowship'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-google-res',
    name: 'Google Research',
    category: 'AI & Analytics',
    tier: 'Tier 1 AI Labs',
    atsProvider: 'custom_rest',
    boardToken: 'google-research',
    careersUrl: 'https://research.google/careers/',
    primaryLocations: ['Bangalore, India', 'Mountain View, CA', 'New York, NY'],
    sampleRoles: ['Student Researcher Intern (Gemini Multi-Modal, AI for Health, Indian Languages)'],
    typicalHiringBar: 'Extreme',
    dsaFocus: ['Top Tier Conference Publications (NeurIPS/ICML/CVPR)', 'JAX / PyTorch Supercomputing', 'Deep Algorithmic Foundations'],
    compensationRange: '₹1,20,000/mo ($65/hr US)',
    internshipSeasons: ['Summer 2026', 'Year-Round'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-ibm-res',
    name: 'IBM Research',
    category: 'AI & Analytics',
    tier: 'Tier 1 AI Labs',
    atsProvider: 'workday',
    boardToken: 'ibm-research',
    careersUrl: 'https://research.ibm.com/careers',
    primaryLocations: ['Bangalore, India', 'Yorktown Heights, NY', 'Cambridge, MA'],
    sampleRoles: ['Research Intern (Quantum Computing & Hybrid Cloud AI)'],
    typicalHiringBar: 'Hard',
    dsaFocus: ['Qiskit Quantum SDK / Python', 'Distributed Cloud Architecture', 'Mathematical Algorithms'],
    compensationRange: '₹75,000/mo ($52/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },

  // ==========================================
  // 5. ENTERPRISE SERVICES & IT (22 Companies)
  // ==========================================
  {
    id: 'comp-tcs',
    name: 'TCS',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'tcs',
    careersUrl: 'https://www.tcs.com/careers/india/entry-level',
    primaryLocations: ['Mumbai, India', 'Bangalore, India', 'Chennai, India', 'Hyderabad, India', 'Pune, India', 'Kolkata, India', 'Delhi NCR, India'],
    sampleRoles: ['TCS Ninja / Digital / Prime Software Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['TCS NQT (National Qualifier Test)', 'Aptitude & Logical Reasoning', 'Basic C / Java / Python Coding'],
    compensationRange: '₹25,000 - ₹35,000/mo (Digital/Prime)',
    internshipSeasons: ['Summer 2026', 'Final Semester Project'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-infosys',
    name: 'Infosys',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'infosys',
    careersUrl: 'https://www.infosys.com/careers/',
    primaryLocations: ['Bangalore, India', 'Mysore, India', 'Pune, India', 'Hyderabad, India', 'Chennai, India'],
    sampleRoles: ['Infosys InStep Intern (Global Internship Program)', 'Specialist Programmer Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['InfyTQ / HackWithInfy Algorithmic Rounds', 'Data Structures (Arrays, Strings, Stacks)', 'Java / Python'],
    compensationRange: '₹30,000 - ₹45,000/mo (InStep: Full Travel + Mysore Campus Stay)',
    internshipSeasons: ['Summer 2026', 'Year-Round'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-wipro',
    name: 'Wipro',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'wipro',
    careersUrl: 'https://careers.wipro.com/',
    primaryLocations: ['Bangalore, India', 'Hyderabad, India', 'Chennai, India', 'Pune, India'],
    sampleRoles: ['Wipro Turbo / Elite Talent Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Wipro NLTH National Talent Hunt', 'Basic Problem Solving', 'OOP Concepts'],
    compensationRange: '₹20,000 - ₹30,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-hcltech',
    name: 'HCLTech',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'hcltech',
    careersUrl: 'https://www.hcltech.com/careers',
    primaryLocations: ['Noida, India', 'Chennai, India', 'Bangalore, India'],
    sampleRoles: ['Graduate Engineer Trainee Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Aptitude & Coding Assessment', 'C++ / Java / Python', 'Database Basics'],
    compensationRange: '₹20,000 - ₹30,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-cognizant',
    name: 'Cognizant',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'cognizant',
    careersUrl: 'https://careers.cognizant.com/global/en',
    primaryLocations: ['Chennai, India', 'Bangalore, India', 'Hyderabad, India', 'Teaneck, NJ'],
    sampleRoles: ['GenC Next / Elevate Software Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['AMCAT Coding Questions', 'Java & Web Development Fundamentals', 'Data Structures'],
    compensationRange: '₹25,000 - ₹35,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-accenture',
    name: 'Accenture',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'workday',
    boardToken: 'accenture',
    careersUrl: 'https://www.accenture.com/in-en/careers/students-graduates',
    primaryLocations: ['Bangalore, India', 'Mumbai, India', 'Hyderabad, India', 'Chicago, IL', 'New York, NY'],
    sampleRoles: ['Advanced App Engineering Intern', 'Cloud & Security Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Cognitive Assessment & Coding', 'Pseudocode Debugging', 'Java / Cloud Fundamentals'],
    compensationRange: '₹30,000 - ₹40,000/mo ($35/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-capgemini',
    name: 'Capgemini',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'capgemini',
    careersUrl: 'https://www.capgemini.com/careers/student-and-graduates/',
    primaryLocations: ['Paris, France', 'Mumbai, India', 'Bangalore, India', 'Pune, India'],
    sampleRoles: ['Software Engineering Intern (Cloud & Digital Services)'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['CoCubes Test Pattern', 'Essay / Behavioral', 'Data Structures Basics'],
    compensationRange: '₹22,000 - ₹32,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-deloitte',
    name: 'Deloitte',
    category: 'Enterprise Services & IT',
    tier: 'Top Finance / Wall St',
    atsProvider: 'custom_rest',
    boardToken: 'deloitte',
    careersUrl: 'https://www2.deloitte.com/us/en/pages/careers/articles/join-deloitte-students-entry-level.html',
    primaryLocations: ['Hyderabad, India', 'Bangalore, India', 'New York, NY', 'Chicago, IL'],
    sampleRoles: ['Technology Consulting Summer Analyst'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Case Study Problem Solving', 'Cloud Architecture / Cyber Security', 'Python / SQL'],
    compensationRange: '₹40,000 - ₹50,000/mo ($42/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-ey',
    name: 'EY',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'ey',
    careersUrl: 'https://www.ey.com/en_gl/careers/students',
    primaryLocations: ['Gurgaon, India', 'Bangalore, India', 'London, UK', 'New York, NY'],
    sampleRoles: ['Technology Consulting Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Aptitude & Analytics', 'Python / PowerBI / SQL', 'Communication & Case Interview'],
    compensationRange: '₹35,000 - ₹45,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-kpmg',
    name: 'KPMG',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'kpmg',
    careersUrl: 'https://kpmg.com/xx/en/home/careers/students.html',
    primaryLocations: ['Bangalore, India', 'Mumbai, India', 'New York, NY'],
    sampleRoles: ['Digital Lighthouse Tech Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Python / ML & Data Pipelines', 'Data Structures', 'Consulting Fit'],
    compensationRange: '₹35,000 - ₹45,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-ltimindtree',
    name: 'LTIMindtree',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'ltimindtree',
    careersUrl: 'https://www.ltimindtree.com/careers/',
    primaryLocations: ['Mumbai, India', 'Bangalore, India', 'Pune, India', 'Warren, NJ'],
    sampleRoles: ['Graduate Engineer Trainee Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Aptitude & Logical Reasoning', 'Java / Python / Cloud Basics', 'OOP'],
    compensationRange: '₹22,000 - ₹30,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-persistent',
    name: 'Persistent Systems',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'persistent-systems',
    careersUrl: 'https://www.persistent.com/careers/',
    primaryLocations: ['Pune, India', 'Bangalore, India', 'Santa Clara, CA'],
    sampleRoles: ['Software Engineering Intern (Cloud & HealthTech Software)'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['Java / C++ Algorithms', 'Data Structures & Trees', 'Database Normalization'],
    compensationRange: '₹25,000 - ₹35,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-mphasis',
    name: 'Mphasis',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'mphasis',
    careersUrl: 'https://www.mphasis.com/home/careers.html',
    primaryLocations: ['Bangalore, India', 'Pune, India', 'New York, NY'],
    sampleRoles: ['Associate Software Engineer Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Aptitude Assessment', 'Java / Python', 'Basic DSA'],
    compensationRange: '₹20,000 - ₹28,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-coforge',
    name: 'Coforge',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'coforge',
    careersUrl: 'https://www.coforge.com/careers',
    primaryLocations: ['Greater Noida, India', 'Bangalore, India', 'Princeton, NJ'],
    sampleRoles: ['Software Engineer Intern (Aviation & Insurance Systems)'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Java / Web Services', 'Aptitude & Logical', 'Basic Data Structures'],
    compensationRange: '₹20,000 - ₹28,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-techm',
    name: 'Tech Mahindra',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'tech-mahindra',
    careersUrl: 'https://careers.techmahindra.com/',
    primaryLocations: ['Pune, India', 'Hyderabad, India', 'Bangalore, India'],
    sampleRoles: ['Associate Software Engineer Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Psychometric & Aptitude', 'Basic Coding', 'Networking / C++'],
    compensationRange: '₹20,000 - ₹28,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-genpact',
    name: 'Genpact',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'genpact',
    careersUrl: 'https://www.genpact.com/careers',
    primaryLocations: ['Gurgaon, India', 'Hyderabad, India', 'New York, NY'],
    sampleRoles: ['Digital Transformation & AI Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Python / SQL / Data Analysis', 'Problem Solving', 'Communication'],
    compensationRange: '₹25,000 - ₹35,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-hexaware',
    name: 'Hexaware',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'hexaware',
    careersUrl: 'https://hexaware.com/careers/',
    primaryLocations: ['Navi Mumbai, India', 'Chennai, India', 'Iselin, NJ'],
    sampleRoles: ['Premier Graduate Trainee Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Aptitude & Coding Test', 'Java / Python / Cloud Basics', 'OOP'],
    compensationRange: '₹22,000 - ₹30,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-cgi',
    name: 'CGI',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'cgi',
    careersUrl: 'https://www.cgi.com/en/careers/students-and-new-graduates',
    primaryLocations: ['Montreal, Canada', 'Bangalore, India', 'Fairfax, VA'],
    sampleRoles: ['Junior Software Developer Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Java / C# / SQL', 'Object Oriented Programming', 'Basic Algorithms'],
    compensationRange: '₹25,000 - ₹35,000/mo ($30/hr US)',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-zensar',
    name: 'Zensar',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'zensar',
    careersUrl: 'https://www.zensar.com/careers',
    primaryLocations: ['Pune, India', 'Bangalore, India', 'San Jose, CA'],
    sampleRoles: ['Junior Engineer Trainee Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Aptitude Assessment', 'Java / Python', 'Basic DSA'],
    compensationRange: '₹20,000 - ₹28,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-dxc',
    name: 'DXC Technology',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'workday',
    boardToken: 'dxc',
    careersUrl: 'https://dxc.com/us/en/about-us/careers',
    primaryLocations: ['Bangalore, India', 'Chennai, India', 'Ashburn, VA'],
    sampleRoles: ['Associate Software Engineer Intern'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['Aptitude & Technical MCQ', 'Cloud Basics & Linux', 'Programming'],
    compensationRange: '₹22,000 - ₹30,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-tataelxsi',
    name: 'Tata Elxsi',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'tata-elxsi',
    careersUrl: 'https://www.tataelxsi.com/careers',
    primaryLocations: ['Bangalore, India', 'Trivandrum, India', 'Pune, India'],
    sampleRoles: ['Embedded Systems & Autonomous Drive Intern'],
    typicalHiringBar: 'Medium',
    dsaFocus: ['C / C++ Embedded Programming', 'Microcontrollers & Linux Kernel', 'DSA Arrays & Trees'],
    compensationRange: '₹25,000 - ₹35,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
  {
    id: 'comp-ltts',
    name: 'L&T Technology Services',
    category: 'Enterprise Services & IT',
    tier: 'Enterprise IT & Services',
    atsProvider: 'custom_rest',
    boardToken: 'ltts',
    careersUrl: 'https://www.ltts.com/careers',
    primaryLocations: ['Vadodara, India', 'Bangalore, India', 'Mysore, India', 'Edison, NJ'],
    sampleRoles: ['Engineering R&D Software Intern (Smart Manufacturing & IoT)'],
    typicalHiringBar: 'Foundational',
    dsaFocus: ['C / C++ / Embedded RTOS', 'Aptitude & Technical Logic', 'Basic Data Structures'],
    compensationRange: '₹22,000 - ₹32,000/mo',
    internshipSeasons: ['Summer 2026'],
    isRealtimeEnabled: true,
  },
];
