import { CompanyInsight, CompanyDataSource } from '../types';

/**
 * Verified Empirical Data Sources & Research Methodology
 * 
 * Transparent attribution of where the informal Layer 2 knowledge graph signals originate.
 */
export const VERIFIED_DATA_SOURCES: Record<string, CompanyDataSource> = {
  SIMPLIFY_PITTS: {
    name: 'Simplify & Pitt CSC Tech Internships Community Repositories',
    category: 'Public Repository',
    urlOrReference: 'github.com/SimplifyJobs/Summer2025-Internships, github.com/pittcsc/Summer2024-Internships',
    lastVerified: 'Summer 2025 / Summer 2026 Cycle',
    description: 'Empirical data on live recruiting timelines, application open dates, ATS platforms, and visa sponsorship policies across 1000+ companies.',
  },
  LEVELS_FYI: {
    name: 'Levels.fyi Verified Intern Compensation Index',
    category: 'Industry Benchmark Platform',
    urlOrReference: 'levels.fyi/internships',
    lastVerified: '2025-2026 Cohort Verified Offer Letters',
    description: 'Crowdsourced, paystub-verified intern hourly rates, corporate housing stipends, and relocation allowances.',
  },
  CODESIGNAL_GCA: {
    name: 'CodeSignal General Coding Assessment (GCA) Evaluation Rubric',
    category: 'Industry Benchmark Platform',
    urlOrReference: 'codesignal.com/frameworks/general-coding-assessment',
    lastVerified: '2025-2026 Standard Framework',
    description: 'Standard 4-task algorithmic assessment score bands (800-850), speed weighting, and proctoring verification standards.',
  },
  LEETCODE_DEBRIEFS: {
    name: 'LeetCode Discuss & Candidate Interview Debriefs',
    category: 'Verified Candidate Debriefs',
    urlOrReference: 'leetcode.com/discuss/interview-experience',
    lastVerified: '2024-2026 Verified Interview Recaps',
    description: 'Candidate debriefs detailing live CoderPad problem types, DSA difficulty tiers, system design expectations, and OA constraints.',
  },
  ENGINEERING_BLOGS: {
    name: 'Official Corporate Engineering Blogs & Leadership Principles',
    category: 'Official Engineering Blog',
    urlOrReference: 'amazon.jobs/principles, stripe.com/blog/engineering, blog.janestreet.com',
    lastVerified: '2025-2026 Published Values',
    description: 'Company-authored engineering standards, architectural values, interview evaluation criteria, and cultural pillars.',
  },
  COMMUNITY_SURVEYS: {
    name: 'Blind & r/csMajors Candidate Hiring Retrospectives',
    category: 'Verified Candidate Debriefs',
    urlOrReference: 'teamblind.com, reddit.com/r/csMajors',
    lastVerified: '2025-2026 Internship Season',
    description: 'Unspoken recruiter filters, target university tiers, GPA cutoffs, class year preferences, and cold resume screening patterns.',
  },
};

export const SEEDED_COMPANY_INSIGHTS: CompanyInsight[] = [
  // ==========================================
  // 1. QUANTITATIVE TRADING & MARKET MAKERS
  // ==========================================
  {
    id: 'comp-jane-street',
    companyName: 'Jane Street',
    aliases: ['Jane Street Capital', 'JSC'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Combinatorics & Probability', 'Type Systems (OCaml)', 'Trees & Graphs', 'Greedy & Math Optimization'],
      focusAreas: 'Clean functional thinking, rigorous logical reasoning, edge-case precision without hand-waving.',
      liveCodingFormat: 'Interactive pair programming (CoderPad/Emacs/Vim). You explain thought processes step-by-step; no compiler during math puzzles.',
      systemDesignExpectation: 'Not asked for undergrad interns; deep focus on program correctness and concurrency fundamentals.',
    },
    oaType: {
      platform: 'No Initial OA / Direct Phone Screen',
      typicalDurationMinutes: 45,
      cutoffScoreDescription: 'Resume-selected candidates directly enter a 45-min technical phone interview with full-time engineers.',
      proctoring: {
        webcamRequired: false,
        screenRecording: false,
        copyPasteDisabled: false,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Intellectual Rigor & Humility', description: 'Candidates must admit when they do not know an answer rather than bluffing.', importance: 'Critical' },
      { trait: 'Functional Programming Passion', description: 'Interest in OCaml, Haskell, or strongly-typed functional paradigms is heavily valued.', importance: 'High' },
      { trait: 'Rapid Collaborative Thinking', description: 'Treats the interviewer as a teammate working through puzzles.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Strong preference for Top 10 CS / Ivy+ / Waterloo / MIT / Cambridge; extraordinary math/Olympiad backgrounds from all schools considered.',
      minimumGpa: '3.7+ strongly favored on resume screening; math/CS transcript scrutinized.',
      priorExperiencePreference: 'Prior top-tier tech/quant internship or prestigious math/coding competition awards (Putnam, USAMO, ICPC).',
      undergradClassStanding: 'Rising Juniors & Seniors; Sophomores with exceptional math competition records.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1, and full work visas).',
      githubOpenSourceWeight: 'High value on compilers, emulators, or typed systems projects.',
    },
    resumeHotkeys: ['OCaml', 'Rust', 'C++', 'Compilers', 'Type Theory', 'ICPC', 'Putnam', 'Concurrency', 'Distributed Systems'],
    redFlags: ['Generic web templates', 'Superficial buzzwords without depth', 'Lack of quantitative metrics'],
    compensationRange: {
      hourlyRateUsd: '$125.00/hr (~$20,000/mo)',
      housingStipendMonthlyUsd: '$3,500/mo or luxury corporate Manhattan apartment',
      relocationBonusUsd: '$3,000 lump sum',
      perks: ['Free gourmet breakfast/lunch/dinner', 'Unlimited barista bar', 'Comprehensive health coverage', 'Round-trip business travel'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Early July (First week of July)',
      typicalCloseDate: 'September (Rolling - first come first served)',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast (Recruiter response within 3-7 business days)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Resume Screening', type: 'Recruiter Call', description: 'Initial review of GPA, coursework, and math/coding achievements.', durationMinutes: 20 },
      { roundNumber: 2, name: 'Technical Phone Screen 1', type: 'Technical Phone Screen', description: 'Probability, algorithmic thinking, and clean data structure design.', durationMinutes: 45 },
      { roundNumber: 3, name: 'Technical Phone Screen 2', type: 'Technical Phone Screen', description: 'Deeper algorithmic problem solving and interactive debugging.', durationMinutes: 45 },
      { roundNumber: 4, name: 'Virtual Onsite (3-4 Rounds)', type: 'Virtual Onsite', description: '3 rounds of paired programming and logic puzzles with traders/SWEs.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.ENGINEERING_BLOGS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-citadel',
    companyName: 'Citadel & Citadel Securities',
    aliases: ['Citadel LLC', 'Citadel Securities', 'Citadel GQS'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'Miami, FL / Chicago, IL / New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Dynamic Programming', 'Graph Theory', 'C++ Low-Latency & Cache Locality', 'Concurrency / Multithreading'],
      focusAreas: 'Optimal time/space complexity, ultra-fast C++ execution, SIMD, lock-free queues, memory layouts.',
      liveCodingFormat: 'Rigorous live coding with strict time limits; expected to write clean, compile-ready C++ or Python.',
      systemDesignExpectation: 'Concurrency primitives, race conditions, memory alignment, OS internals.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: 'HackerRank 2 Hard algorithmic problems. Expectation: 100% test cases passed with strict O(N) or O(N log N) time limits.',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: true,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Extreme Performance Orientation', description: 'Relentless drive for excellence, speed, and competitive execution.', importance: 'Critical' },
      { trait: 'Deep Systems Understanding', description: 'Knowledge of hardware architecture, CPU cache lines, and network buffers.', importance: 'High' },
      { trait: 'Precision Under Pressure', description: 'Ability to debug complex edge cases rapidly without panic.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Heavily targets Top 15 CS & Engineering universities; Top GPA applicants from state schools considered.',
      minimumGpa: '3.6+ strongly screened.',
      priorExperiencePreference: 'Top tech internship (Meta, Google, Palantir) or prior finance/HFT experience.',
      undergradClassStanding: 'Rising Juniors and Seniors; Masters/PhD for Quantitative Research.',
      internationalVisaOpenness: 'High (Full visa sponsorship provided).',
      githubOpenSourceWeight: 'High value for low-level systems (C++, Rust, Linux kernel).',
    },
    resumeHotkeys: ['C++20', 'Low-Latency', 'Concurrency', 'Multithreading', 'Memory Management', 'Lock-Free', 'Distributed Systems', 'CUDA'],
    redFlags: ['Surface-level Python only for SWE roles', 'Lack of systems knowledge', 'No quantitative impact'],
    compensationRange: {
      hourlyRateUsd: '$120.00/hr (~$19,200/mo)',
      housingStipendMonthlyUsd: '$3,000/mo or luxury corporate apartment (Four Seasons / luxury high-rise)',
      relocationBonusUsd: '$5,000 signing/relocation bonus',
      perks: ['Catered 3 meals/day', 'Luxury intern offsite summit (e.g., Palm Beach/Disney World)', 'Full travel reimbursement'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Late June / Early July',
      typicalCloseDate: 'September (Fills quickly)',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast (OA automated upon application submission)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Proctored HackerRank OA', type: 'OA', description: '2 LeetCode Hard DSA questions (90 min).', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen 1', type: 'Technical Phone Screen', description: 'Live coding + C++ low-level systems & memory architecture.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Technical Phone Screen 2', type: 'Technical Phone Screen', description: 'Advanced algorithms, concurrency, and distributed architecture.', durationMinutes: 60 },
      { roundNumber: 4, name: 'Virtual Onsite (3-4 Rounds)', type: 'Virtual Onsite', description: 'Coding + systems + behavioral fit with engineering leads.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-hrt',
    companyName: 'Hudson River Trading',
    aliases: ['HRT'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['C++ Systems Programming', 'Bit Manipulation', 'Graph Algorithms', 'Dynamic Programming', 'OS Internals'],
      focusAreas: 'Linux kernel bypass, network socket programming, assembly / CPU architecture, memory efficiency.',
      liveCodingFormat: 'Writing idiomatic, efficient C++ or Python; in-depth discussion of assembly disassembly and cache misses.',
      systemDesignExpectation: 'Designing a real-time order book, message queue, or packet parser.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 120,
      cutoffScoreDescription: 'HackerRank with 3 algorithmic problems + multiple-choice C++/OS systems architecture questions.',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: true,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Flat Hierarchy & Collegiality', description: 'No dress code; casual, collaborative, math and tech nerd culture.', importance: 'High' },
      { trait: 'Engineering Craftsmanship', description: 'Extreme pride in building proprietary, zero-overhead systems.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'MIT, Stanford, CMU, Berkeley, Waterloo, UIUC, Harvard, Caltech top priority.',
      minimumGpa: '3.7+ expected.',
      priorExperiencePreference: 'High preference for strong systems projects or prior HFT/tech internship.',
      undergradClassStanding: 'Rising Juniors, Seniors, and Masters students.',
      internationalVisaOpenness: 'High (Full sponsorship).',
      githubOpenSourceWeight: 'Extremely high for C++, Rust, emulator, or networking codebases.',
    },
    resumeHotkeys: ['C++', 'Linux Kernel', 'Sockets', 'TCP/IP', 'Bypass', 'Memory Optimization', 'Assembly', 'Concurrency'],
    redFlags: ['No low-level systems experience', 'Unfamiliarity with pointer arithmetic and memory layouts'],
    compensationRange: {
      hourlyRateUsd: '$125.00/hr (~$20,000/mo)',
      housingStipendMonthlyUsd: 'Full luxury corporate housing provided in Manhattan',
      relocationBonusUsd: '$3,000 lump sum',
      perks: ['Gourmet private chef dining', 'Company weekend trips', 'Full benefits package'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Early July',
      typicalCloseDate: 'September/October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '120 min C++ / Algorithms / OS test.', durationMinutes: 120 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Deep dive into C++ and algorithmic complexity.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Systems programming, algorithms, and team fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-two-sigma',
    companyName: 'Two Sigma',
    aliases: ['Two Sigma Investments'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Data Structures & Algorithms', 'Distributed Systems', 'Java/C++ Memory Model', 'Graphs & Trees'],
      focusAreas: 'Clean object-oriented design, distributed data processing, clean API abstractions.',
      liveCodingFormat: 'CoderPad coding + deep questions about algorithmic tradeoffs and data structure selection.',
      systemDesignExpectation: 'Basic distributed systems (caching, load balancing, sharding).',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 85,
      cutoffScoreDescription: '2 algorithmic problems + CS fundamentals questions. 100% test cases expected.',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: true,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Scientific & Academic Approach', description: 'Treats software and financial markets as empirical scientific disciplines.', importance: 'Critical' },
      { trait: 'Clean Code Architecture', description: 'Values elegant, maintainable code over quick-and-dirty hacks.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top 20 CS & Ivy League; strong CS fundamentals from any university considered.',
      minimumGpa: '3.5+ required on transcript review.',
      priorExperiencePreference: 'Prior software engineering internship.',
      undergradClassStanding: 'Rising Juniors and Seniors.',
      internationalVisaOpenness: 'High.',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['Java', 'C++', 'Distributed Systems', 'Algorithms', 'Data Structures', 'Spark', 'SQL'],
    redFlags: ['Poor code formatting', 'Inability to explain time/space complexities accurately'],
    compensationRange: {
      hourlyRateUsd: '$110.00/hr (~$17,500/mo)',
      housingStipendMonthlyUsd: '$3,000/mo or luxury corporate apartment in NYC',
      relocationBonusUsd: '$2,500 lump sum',
      perks: ['Free gourmet breakfast/lunch', 'Educational seminars', 'Hackathon with prizes'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July',
      typicalCloseDate: 'October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Moderate',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: 'Algorithmic assessment (85 min).', durationMinutes: 85 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Algorithmic problem solving and data structure design.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Data structures, design, and culture fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // 2. BIG TECH & FAANG+
  // ==========================================
  {
    id: 'comp-google',
    companyName: 'Google',
    aliases: ['Google LLC', 'Alphabet', 'Google DeepMind'],
    tier: 'Tier 1 Big Tech / FAANG+',
    industry: 'Cloud / AI / Big Tech',
    headquarters: 'Mountain View, CA / New York, NY / Seattle, WA',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Graphs (BFS/DFS/Dijkstra)', 'Dynamic Programming', 'Trees & Tries', 'Sliding Window / Two Pointers'],
      focusAreas: 'Clean code readability, asymptotic time/space complexity analysis, communication and edge case handling.',
      liveCodingFormat: 'Google Docs / Google Meet interactive coding. No compiler or IDE autocompletion; syntax must be accurate.',
      systemDesignExpectation: 'Not tested for SWE interns; pure algorithmic problem solving.',
    },
    oaType: {
      platform: 'Custom Proctored Platform',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: 'Google Online Challenge (GOC): 2 algorithmic problems. Passing all visible and hidden test cases with optimal time complexity.',
      proctoring: {
        webcamRequired: false,
        screenRecording: false,
        copyPasteDisabled: false,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Googliness & Team Collaboration', description: 'Navigating ambiguity, being receptive to feedback, intellectual humility, and doing the right thing.', importance: 'Critical' },
      { trait: 'Structured Communication', description: 'Talking out loud before writing a single line of code; validating assumptions.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base; strong diversity programs (STEP for freshmen/sophomores). Top schools get faster recruiter screens.',
      minimumGpa: 'No strict GPA cutoff on application, but >3.3 recommended.',
      priorExperiencePreference: 'Helpful but strong personal projects or research can secure interviews.',
      undergradClassStanding: 'STEP Interns: Freshmen/Sophomores. SWE Interns: Rising Juniors (Penultimate year).',
      internationalVisaOpenness: 'High (Full J-1 / CPT / OPT sponsorship).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['C++', 'Python', 'Java', 'Algorithms', 'Distributed Systems', 'Machine Learning', 'Data Structures'],
    redFlags: ['Writing code before clarifying the question', 'Ignoring interviewer hints', 'Unverified resume claims'],
    compensationRange: {
      hourlyRateUsd: '$53.00 - $60.00/hr (~$9,000/mo)',
      housingStipendMonthlyUsd: '$9,000 total lump sum stipend or corporate housing provided',
      relocationBonusUsd: 'Full flight booking & luggage coverage',
      perks: ['Free 3 gourmet meals/day + microkitchens', 'Access to internal Google compute/GPUs', 'Campus gym & massage'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Late August / Early September',
      typicalCloseDate: 'November (or until project matching cap is reached)',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Moderate (Project search matching phase can take 2-6 weeks)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Google Online Challenge (GOC)', type: 'OA', description: '2 LeetCode Medium/Hard algorithmic questions.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen 1', type: 'Technical Phone Screen', description: '45-min live coding on Google Docs with SWE.', durationMinutes: 45 },
      { roundNumber: 3, name: 'Technical Phone Screen 2', type: 'Technical Phone Screen', description: '45-min live coding on Google Docs with SWE.', durationMinutes: 45 },
      { roundNumber: 4, name: 'Host Matching (Project Search)', type: 'Behavioral / Values Fit', description: 'Conversations with engineering managers to match projects.', durationMinutes: 30 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-meta',
    companyName: 'Meta',
    aliases: ['Meta Platforms', 'Facebook', 'Instagram', 'Reality Labs'],
    tier: 'Tier 1 Big Tech / FAANG+',
    industry: 'Cloud / AI / Big Tech',
    headquarters: 'Menlo Park, CA / Seattle, WA / New York, NY',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Top Meta Tagged LeetCode Questions', 'Graph Traversals', 'Binary Trees', 'Array & String Manipulation', 'DP'],
      focusAreas: 'Fast implementation speed (solving 2 LeetCode Mediums in 35 minutes bug-free), clean code, zero compilation errors.',
      liveCodingFormat: 'CoderPad without code execution. Interviewer reads through code manually to verify correctness.',
      systemDesignExpectation: 'Not tested for undergrad interns.',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal General Coding Assessment. Cutoff score: 830+ typical threshold for recruiter screen (840+ auto-advances).',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: true,
        audioMonitored: true,
      },
    },
    cultureTraits: [
      { trait: 'Move Fast & Execute', description: 'High bias for action, swift implementation, and delivering tangible impact.', importance: 'Critical' },
      { trait: 'Be Bold & Direct', description: 'Clear, direct communication without excessive corporate pleasantries.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting; Meta University (Meta U) for underrepresented underclassmen.',
      minimumGpa: 'No GPA requirement (Meta does not look at GPA).',
      priorExperiencePreference: 'High preference for strong software development projects or prior internships.',
      undergradClassStanding: 'Rising Juniors / Penultimate year students for SWE Internship; Freshmen/Sophomores for Meta U.',
      internationalVisaOpenness: 'High (Sponsors J-1, CPT, OPT).',
      githubOpenSourceWeight: 'Moderate.',
    },
    resumeHotkeys: ['React', 'Python', 'C++', 'GraphQL', 'Distributed Systems', 'PyTorch', 'Hack / PHP', 'SQL'],
    redFlags: ['Slow typing or hesitating on standard LeetCode Medium algorithms', 'Syntax bugs in basic array/string loops'],
    compensationRange: {
      hourlyRateUsd: '$56.00 - $62.00/hr (~$9,500/mo)',
      housingStipendMonthlyUsd: '$2,000 - $3,000/mo stipend or luxury corporate housing',
      relocationBonusUsd: '$1,000 - $2,000 travel/wellness allowance',
      perks: ['Free gourmet meals & barista drinks', 'Free Meta Quest VR headsets for testing', 'Shuttle transportation network'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Late August / Early September',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast (CodeSignal invite sent automatically to qualified applicants)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA Online Assessment', type: 'OA', description: '70-min proctored CodeSignal GCA (Target: 830+).', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: '2 LeetCode Medium questions in 45 min on CoderPad.', durationMinutes: 45 },
      { roundNumber: 3, name: 'Virtual Onsite (2 Technical Rounds)', type: 'Virtual Onsite', description: '2 back-to-back 45-min live coding interviews (2 questions each).', durationMinutes: 90 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.CODESIGNAL_GCA, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-amazon',
    companyName: 'Amazon',
    aliases: ['Amazon.com', 'AWS', 'Amazon Web Services'],
    tier: 'Tier 1 Big Tech / FAANG+',
    industry: 'Cloud / AI / Big Tech',
    headquarters: 'Seattle, WA / Arlington, VA / Austin, TX / Bay Area',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['BFS/DFS Graphs', 'Priority Queues / Heaps', 'Trees', 'HashMaps / Two Pointers', 'Greedy Algorithms'],
      focusAreas: 'Clean standard LeetCode Medium algorithms + heavy focus on Amazon 16 Leadership Principles in every round.',
      liveCodingFormat: 'Amazon Chime with live collaborative coding editor.',
      systemDesignExpectation: 'Object-Oriented Design (OOD) basics (e.g. Design Parking Lot, File System).',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 120,
      cutoffScoreDescription: 'Part 1: 2 DSA coding questions (70 min). Part 2: Work Simulation & Leadership Principles assessment (20 min).',
      proctoring: {
        webcamRequired: false,
        screenRecording: false,
        copyPasteDisabled: false,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: '16 Leadership Principles (LPs)', description: 'Customer Obsession, Ownership, Bias for Action, Deliver Results, Dive Deep are rigorously evaluated.', importance: 'Critical' },
      { trait: 'STAR Method Behavioral Answers', description: 'Situation, Task, Action, Result with quantified metrics is required for all behavioral questions.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Wide hiring pool across all accredited universities; massive headcount.',
      minimumGpa: '3.0+ recommended; rarely scrutinized if OA score is strong.',
      priorExperiencePreference: 'Open to first-time interns with solid CS fundamentals.',
      undergradClassStanding: 'Rising Juniors, Seniors, and Masters students (Amazon Propel for underclassmen).',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate.',
    },
    resumeHotkeys: ['Java', 'AWS', 'Python', 'Microservices', 'Distributed Systems', 'SQL', 'Docker', 'REST API'],
    redFlags: ['Saying "we" instead of "I" in behavioral stories', 'Ignoring Customer Obsession or Ownership in scenarios'],
    compensationRange: {
      hourlyRateUsd: '$53.00 - $60.00/hr (~$9,000/mo)',
      housingStipendMonthlyUsd: '$2,425/mo monthly housing stipend or corporate apartments',
      relocationBonusUsd: 'Travel booking provided',
      perks: ['Subsidized public transit', 'Employee discounts', 'AWS cloud credits'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Late July / August',
      typicalCloseDate: 'February/March (Massive rolling waves)',
      rollingBasis: true,
      urgencyRating: 'STANDARD_FALL',
      recruiterVelocity: 'Fast automated OA pipeline (OA1 -> OA2 -> Final 1x30min or 3x45min interview)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Online Assessment 1 (OA1: Coding & Work Simulation)', type: 'OA', description: '2 Coding questions + Work Style assessment.', durationMinutes: 120 },
      { roundNumber: 2, name: 'Final Virtual Round', type: 'Virtual Onsite', description: '1x45min or 3x45min rounds covering DSA and Leadership Principles.', durationMinutes: 45 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.ENGINEERING_BLOGS, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-apple',
    companyName: 'Apple',
    aliases: ['Apple Inc.', 'Apple Park'],
    tier: 'Tier 1 Big Tech / FAANG+',
    industry: 'Cloud / AI / Big Tech',
    headquarters: 'Cupertino, CA / Austin, TX / Seattle, WA',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['C/C++ Systems Programming', 'Memory Management', 'Algorithms', 'Hardware/Software Boundary', 'Swift / Objective-C'],
      focusAreas: 'Team-specific interviewing. Hardware teams test C/C++, OS, and memory; Cloud teams test Distributed Systems and Java/Python.',
      liveCodingFormat: 'WebEx / CoderPad with hiring managers and senior architects.',
      systemDesignExpectation: 'Basic low-level systems or microservices architecture depending on the group.',
    },
    oaType: {
      platform: 'No Initial OA / Direct Phone Screen',
      typicalDurationMinutes: 45,
      cutoffScoreDescription: 'Apple does not use unified company-wide OAs; individual team managers review resumes and initiate screens.',
      proctoring: {
        webcamRequired: false,
        screenRecording: false,
        copyPasteDisabled: false,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Extreme Discretion & Secrecy', description: 'High respect for confidentiality and user privacy.', importance: 'Critical' },
      { trait: 'Obsession with User Experience & Craft', description: 'Attention to detail, pixel perfection, and flawless performance.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS and Engineering schools heavily represented; strong direct networking with team leads helps bypass recruiter queue.',
      minimumGpa: '3.3+ recommended.',
      priorExperiencePreference: 'High value on practical domain depth (e.g. CoreOS, Metal, Swift, CoreML, Compiler projects).',
      undergradClassStanding: 'Rising Juniors, Seniors, and Graduate students.',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'High for systems, Swift, or LLVM contributions.',
    },
    resumeHotkeys: ['C', 'C++', 'Swift', 'Objective-C', 'Metal', 'CoreOS', 'Kernel', 'Memory Management', 'Python', 'ML'],
    redFlags: ['Generic resumes not tailored to the specific team requisition', 'Inability to explain memory leaks / pointers'],
    compensationRange: {
      hourlyRateUsd: '$50.00 - $58.00/hr (~$8,500/mo)',
      housingStipendMonthlyUsd: '$1,000/mo + fully paid luxury corporate housing in Silicon Valley',
      relocationBonusUsd: 'Full travel provided',
      perks: ['Subsidized Apple Caffè Macs', 'Significant hardware discounts', 'Wellness and fitness center'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September (Team-by-team requisitions open through Spring)',
      typicalCloseDate: 'April (Rolling team requisitions)',
      rollingBasis: true,
      urgencyRating: 'STANDARD_FALL',
      recruiterVelocity: 'Moderate (Individual team hiring cycles)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Team Recruiter Screen', type: 'Recruiter Call', description: 'Team fit, domain background, and logistics.', durationMinutes: 30 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Domain-specific coding and systems questions.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3-4 Team Rounds)', type: 'Virtual Onsite', description: 'Technical depth, live coding, and group architectural review.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-microsoft',
    companyName: 'Microsoft',
    aliases: ['Microsoft Corporation', 'MSFT', 'Azure'],
    tier: 'Tier 1 Big Tech / FAANG+',
    industry: 'Cloud / AI / Big Tech',
    headquarters: 'Redmond, WA / Bellevue, WA / Sunnyvale, CA',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['Trees & Graphs', 'Linked Lists & Arrays', 'Dynamic Programming', 'Recursion & Backtracking'],
      focusAreas: 'Clean code structure, error handling, adaptability, and growth mindset.',
      liveCodingFormat: 'Microsoft Teams collaborative coding session.',
      systemDesignExpectation: 'Basic conceptual scalability for Azure teams.',
    },
    oaType: {
      platform: 'Codility',
      typicalDurationMinutes: 80,
      cutoffScoreDescription: 'Codility assessment with 2-3 algorithmic problems. Clean, edge-case-tested code is evaluated.',
      proctoring: {
        webcamRequired: false,
        screenRecording: false,
        copyPasteDisabled: true,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Growth Mindset', description: 'Openness to learning, continuous improvement, and constructive feedback.', importance: 'Critical' },
      { trait: 'Empathy & Inclusivity', description: 'Building products that empower every person on the planet.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting; strong university recruiting partnerships nationwide.',
      minimumGpa: '3.0+ recommended.',
      priorExperiencePreference: 'Prior experience is a plus, but strong CS projects qualify.',
      undergradClassStanding: 'Explore Interns: Freshmen/Sophomores. SWE Interns: Rising Juniors (Penultimate year).',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['C#', '.NET', 'TypeScript', 'Azure', 'C++', 'Java', 'Python', 'React', 'Distributed Systems'],
    redFlags: ['Arrogance or rejecting interviewer hints', 'Unclean code without comments or structure'],
    compensationRange: {
      hourlyRateUsd: '$48.00 - $55.00/hr (~$8,000/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments in Redmond',
      relocationBonusUsd: '$1,200 travel/wellness bonus',
      perks: ['Free public transit Orca card', 'Xbox game pass & hardware perks', 'World-class campus amenities'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Early August',
      typicalCloseDate: 'December',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast (Early applicants get screened in September/October interview days)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Codility Online Assessment', type: 'OA', description: '2-3 algorithmic coding challenges (80 min).', durationMinutes: 80 },
      { roundNumber: 2, name: 'First Round Phone Screen', type: 'Technical Phone Screen', description: 'DSA problem solving + behavioral questions.', durationMinutes: 45 },
      { roundNumber: 3, name: 'Final Virtual Interview Day (2-3 Rounds)', type: 'Virtual Onsite', description: '2-3 back-to-back 45-min rounds with Azure/Office/Core OS teams.', durationMinutes: 135 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // 3. ELITE ENTERPRISE & CLOUD UNICORNS
  // ==========================================
  {
    id: 'comp-stripe',
    companyName: 'Stripe',
    aliases: ['Stripe Inc.'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'San Francisco, CA / Seattle, WA / Remote',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Practical API Design', 'Data Parsing & Transformation', 'Refactoring Real Codebases', 'Concurrency & Rate Limiting'],
      focusAreas: 'Practical engineering over theoretical LeetCode trivia. You are given a realistic mini-codebase, real unit tests, and asked to implement features and handle edge cases.',
      liveCodingFormat: 'Bring Your Own Environment (BYOE). You code in your own IDE (VS Code/IntelliJ), compile, and run real unit test suites via screen share.',
      systemDesignExpectation: 'System architecture / API design interview is common for interns (e.g. Design a webhook delivery engine or idempotent payment API).',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 60,
      cutoffScoreDescription: 'Practical string parsing and state-machine problem with real-world business logic.',
      proctoring: {
        webcamRequired: false,
        screenRecording: false,
        copyPasteDisabled: false,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Meticulous Craftsmanship & Writing', description: 'High bar for clean variable names, documentation, and user-facing clarity.', importance: 'Critical' },
      { trait: 'Macro Thinking & Customer Empathy', description: 'Understanding how code impacts global GDP and economic infrastructure.', importance: 'High' },
      { trait: 'First-Principles Pragmatism', description: 'Prefers simple, robust solutions over overly clever abstractions.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Strong representation from Waterloo, Stanford, Berkeley, MIT, and self-taught open source creators.',
      minimumGpa: 'No GPA cutoff (focus is strictly on code quality and project depth).',
      priorExperiencePreference: 'High preference for candidates who have shipped real products or production systems.',
      undergradClassStanding: 'Rising Juniors, Seniors, and Co-op students.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1, and remote contracts).',
      githubOpenSourceWeight: 'Extremely high (Strong GitHub repos get instant recruiter priority).',
    },
    resumeHotkeys: ['Ruby', 'Go', 'TypeScript', 'Java', 'APIs', 'Idempotency', 'Distributed Systems', 'PostgreSQL', 'Docker'],
    redFlags: ['Writing sloppy code with poor variable names', 'Inability to navigate your own local dev environment', 'Ignoring failing unit tests'],
    compensationRange: {
      hourlyRateUsd: '$68.00 - $75.00/hr (~$11,500/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments',
      relocationBonusUsd: '$2,000 relocation stipend',
      perks: ['Remote office setup budget ($1,500)', 'Wellness & fitness reimbursement', 'Comprehensive benefits'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Late August / Early September',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Practical HackerRank OA', type: 'OA', description: '60-min practical data transformation challenge.', durationMinutes: 60 },
      { roundNumber: 2, name: 'Recruiter Chat', type: 'Recruiter Call', description: 'Background and expectations.', durationMinutes: 30 },
      { roundNumber: 3, name: 'Live Coding 1: Bug Squashing / Feature Dev', type: 'Technical Phone Screen', description: 'Real-world coding in your own IDE with test suites.', durationMinutes: 60 },
      { roundNumber: 4, name: 'Virtual Onsite (3 Rounds: Coding + Integration + Behavioral)', type: 'Virtual Onsite', description: 'Practical coding + API design + Stripe operating principles.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.ENGINEERING_BLOGS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-databricks',
    companyName: 'Databricks',
    aliases: ['Databricks Inc.'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'San Francisco, CA / Mountain View, CA / Seattle, WA',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['C++ & Scala Distributed Systems', 'Query Execution Engines', 'Concurreny & Locks', 'Complex Graph & Tree Traversal'],
      focusAreas: 'High algorithmic rigor, database internals, cache optimization, memory management, and compiler fundamentals.',
      liveCodingFormat: 'CoderPad coding with senior distributed systems engineers.',
      systemDesignExpectation: 'Strong systems and concurrency primitives testing.',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA. Minimum passing threshold: 840+ (One of the strictest score cutoffs in tech).',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: true,
        audioMonitored: true,
      },
    },
    cultureTraits: [
      { trait: 'Technical Brilliance & Innovation', description: 'Founded by the creators of Apache Spark and Delta Lake; values deep technical mastery.', importance: 'Critical' },
      { trait: 'Customer Impact at Scale', description: 'Building the foundational data and AI intelligence platform for Global 2000 enterprises.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS programs (Berkeley, Stanford, CMU, Waterloo, UIUC, MIT heavily recruited).',
      minimumGpa: '3.5+ preferred on resume review.',
      priorExperiencePreference: 'High preference for prior systems or big tech internship experience.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters, and PhDs.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'High for databases, distributed systems, and compiler projects.',
    },
    resumeHotkeys: ['C++', 'Scala', 'Distributed Systems', 'Spark', 'Query Engine', 'Storage Engine', 'Raft', 'Rust', 'JVM Internals'],
    redFlags: ['Weak understanding of thread safety and memory bounds', 'CodeSignal score below 820'],
    compensationRange: {
      hourlyRateUsd: '$65.00 - $72.00/hr (~$11,000/mo)',
      housingStipendMonthlyUsd: '$3,000/mo housing stipend or luxury corporate housing',
      relocationBonusUsd: '$2,000 travel bonus',
      perks: ['Free gourmet lunches and dinners', 'High-end developer hardware', 'Full company offsite participation'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Late July / August',
      typicalCloseDate: 'October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min GCA (Expectation: 840+).', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Hard algorithmic problem solving and systems reasoning.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Algorithms + Systems Architecture + Team Fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.CODESIGNAL_GCA, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-palantir',
    companyName: 'Palantir Technologies',
    aliases: ['Palantir'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'Denver, CO / New York, NY / Palo Alto, CA / Washington, DC',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Data Structure Design', 'System Decomposition', 'Graph Traversals', 'Concurrency & Real-time Pipelines'],
      focusAreas: 'Decomposition: The famous Palantir "Decomposition" round tests ability to take a massive open-ended problem and break it down into clean data models.',
      liveCodingFormat: 'Karat technical screening followed by live paired architecture and coding with Forward Deployed SWEs.',
      systemDesignExpectation: 'High for an internship (focuses on realistic component design and trade-offs).',
    },
    oaType: {
      platform: 'Karat',
      typicalDurationMinutes: 60,
      cutoffScoreDescription: '45-min live Karat interview: 3-5 rapid-fire systems/CS questions + 2 algorithmic coding problems.',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: false,
        audioMonitored: true,
      },
    },
    cultureTraits: [
      { trait: 'Mission-Driven Pragmatism', description: 'Passion for solving critical real-world problems in defense, healthcare, and infrastructure.', importance: 'Critical' },
      { trait: 'High Autonomy & Ownership', description: 'Engineers deployed directly into high-stakes customer environments.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Strong representation across top CS and engineering programs; hires based heavily on Karat and Decomposition performance.',
      minimumGpa: 'No strict cutoff; problem-solving ability prioritized.',
      priorExperiencePreference: 'Practical full-stack or backend projects with demonstrable scale.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'Moderate (US Citizen / Permanent Resident required for specific Defense/Gov deployment roles; Commercial roles sponsor visas).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['TypeScript', 'Java', 'Python', 'C++', 'Distributed Systems', 'React', 'Microservices', 'GraphQL', 'PostgreSQL'],
    redFlags: ['Getting paralyzed by ambiguous problem prompts', 'Inability to write modular, testable code'],
    compensationRange: {
      hourlyRateUsd: '$60.00 - $67.00/hr (~$10,000/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing allowance or corporate housing',
      relocationBonusUsd: '$1,500 travel allowance',
      perks: ['Full catered meals', 'Comprehensive health & wellness coverage', 'Top-tier tech setup'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July / August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Karat Technical Screen', type: 'Technical Phone Screen', description: 'Live coding and CS concepts with Karat interviewer.', durationMinutes: 60 },
      { roundNumber: 2, name: 'Decomposition Round', type: 'Virtual Onsite', description: 'Open-ended real-world system architecture design.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Algorithmic Coding Round', type: 'Virtual Onsite', description: 'Complex data structures and algorithms.', durationMinutes: 60 },
      { roundNumber: 4, name: 'Values & Mission Fit', type: 'Behavioral / Values Fit', description: 'Discussion of Palantir mission and personal alignment.', durationMinutes: 45 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-openai',
    companyName: 'OpenAI',
    aliases: ['OpenAI LLC'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Applied AI & Foundation Models',
    headquarters: 'San Francisco, CA',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['PyTorch CUDA Kernels', 'Distributed GPU Training', 'Systems & Networking', 'Algorithmic Optimization'],
      focusAreas: 'Distributed AI systems, transformer architecture optimizations, tensor parallelism, high-throughput inference.',
      liveCodingFormat: 'Practical systems coding, PyTorch implementation, and debugging GPU distributed memory bottlenecks.',
      systemDesignExpectation: 'High: Scalable inference serving, KV cache management, model checkpointing.',
    },
    oaType: {
      platform: 'Custom Proctored Platform',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: 'Practical machine learning systems or high-performance computing challenge.',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: false,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Safe & Beneficial AGI Focus', description: 'Alignment with long-term mission of creating safe artificial general intelligence.', importance: 'Critical' },
      { trait: 'High Intensity & Scientific Curiosity', description: 'Rapid experimentation, reading research papers, and fast engineering turnaround.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS/AI research universities (Stanford, MIT, Berkeley, CMU, Toronto, Oxford).',
      minimumGpa: 'Not explicitly published; strong research publications (NeurIPS, ICML, ICLR) heavily prioritized for research internships.',
      priorExperiencePreference: 'Prior experience at top AI lab or high-scale infrastructure company.',
      undergradClassStanding: 'Undergrads with outstanding ML/systems projects, Masters, and PhD students.',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'Extremely high (Custom CUDA kernels, transformer libraries, distributed inference).',
    },
    resumeHotkeys: ['PyTorch', 'CUDA', 'Triton', 'Distributed Systems', 'Transformers', 'GPU Cluster', 'C++', 'Python', 'Ray'],
    redFlags: ['Only using scikit-learn without understanding low-level tensor operations', 'Lack of systems knowledge'],
    compensationRange: {
      hourlyRateUsd: '$75.00 - $90.00/hr (~$13,500/mo)',
      housingStipendMonthlyUsd: '$3,000/mo housing stipend in San Francisco',
      relocationBonusUsd: '$3,000 lump sum',
      perks: ['Daily gourmet dining', 'Unlimited access to state-of-the-art model clusters and GPUs', 'Full health coverage'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'October (Extremely limited intern cohort)',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Technical Take-Home / Screen', type: 'OA', description: 'Practical ML/Systems implementation challenge.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Systems algorithms and PyTorch tensor operations.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3-4 Rounds)', type: 'Virtual Onsite', description: 'Distributed systems, deep learning internals, and mission alignment.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.ENGINEERING_BLOGS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // 4. TOP FINANCE & WALL STREET INSTITUTIONS
  // ==========================================
  {
    id: 'comp-goldman-sachs',
    companyName: 'Goldman Sachs',
    aliases: ['GS', 'Goldman Sachs & Co.'],
    tier: 'Top Finance / Wall St',
    industry: 'Investment Banking / Finance',
    headquarters: 'New York, NY / Salt Lake City, UT / Dallas, TX',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['Arrays & HashMaps', 'Dynamic Programming', 'SQL & Database Queries', 'Math & Probability Puzzles'],
      focusAreas: 'Clean Java/C++/Python, SQL database optimization, financial calculation precision.',
      liveCodingFormat: 'CoderPad / Zoom interactive technical interview.',
      systemDesignExpectation: 'Basic database schema design and REST architecture.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 120,
      cutoffScoreDescription: 'HackerRank OA: 2 Coding questions + Math/Probability aptitude + CS core concepts. Strict evaluation of all test cases.',
      proctoring: {
        webcamRequired: true,
        screenRecording: true,
        copyPasteDisabled: true,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'Client Focus & Professional Integrity', description: 'High standards of professionalism, risk awareness, and compliance.', importance: 'Critical' },
      { trait: 'Teamwork & Diversity', description: 'Collaborative mindset across global engineering teams.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Ivy League, Top 25 CS, and key regional core recruiting partner universities.',
      minimumGpa: '3.4+ strictly screened on resume submission.',
      priorExperiencePreference: 'Prior finance, fintech, or corporate software experience.',
      undergradClassStanding: 'Rising Juniors (Summer Analyst program is strictly for penultimate year students for full-time conversion).',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, H-1B for engineering roles).',
      githubOpenSourceWeight: 'Moderate.',
    },
    resumeHotkeys: ['Java', 'Spring Boot', 'Python', 'C++', 'SQL', 'PostgreSQL', 'Microservices', 'REST APIs', 'Financial Data'],
    redFlags: ['GPA below 3.3', 'Unprofessional presentation', 'Inability to explain time complexity of basic data structures'],
    compensationRange: {
      hourlyRateUsd: '$50.00 - $58.00/hr (~$8,500/mo)',
      housingStipendMonthlyUsd: '$2,000/mo housing stipend or relocation package',
      relocationBonusUsd: '$1,000 relocation stipend',
      perks: ['Onsite gym and dining', 'Mentorship and executive speaker series', 'Global analyst network'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July 1st (One of the earliest Wall Street openings)',
      typicalCloseDate: 'September / October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast initial HackerRank distribution',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank Assessment', type: 'OA', description: '2 Coding questions + Math & CS MCQs (120 min).', durationMinutes: 120 },
      { roundNumber: 2, name: 'HireVue Video Interview', type: 'Behavioral / Values Fit', description: 'Asynchronous video recorded behavioral responses.', durationMinutes: 30 },
      { roundNumber: 3, name: 'Superday (2-3 Technical & Fit Rounds)', type: 'Virtual Onsite', description: 'Live coding + system/database design + behavioral interviews.', durationMinutes: 120 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.COMMUNITY_SURVEYS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-bloomberg',
    companyName: 'Bloomberg LP',
    aliases: ['Bloomberg'],
    tier: 'Top Finance / Wall St',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'New York, NY / London, UK / San Francisco, CA',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['C++ / Python Data Structures', 'Linked Lists & Trees', 'Two Pointers & Hash Tables', 'Concurrency & Low-Latency Basics'],
      focusAreas: 'Clean memory management, real-time data streaming fundamentals, C++ pointer mechanics, and problem-solving velocity.',
      liveCodingFormat: 'HackerRank CodePair live with Bloomberg engineers.',
      systemDesignExpectation: 'Basic design of news feeds, alert systems, or high-throughput caches.',
    },
    oaType: {
      platform: 'No Initial OA / Direct Phone Screen',
      typicalDurationMinutes: 45,
      cutoffScoreDescription: 'Resume screening directly leads to technical phone screen with Bloomberg engineers.',
      proctoring: {
        webcamRequired: false,
        screenRecording: false,
        copyPasteDisabled: false,
        audioMonitored: false,
      },
    },
    cultureTraits: [
      { trait: 'High Speed & Reliability', description: 'Powering 350,000+ Bloomberg Terminal users worldwide with zero downtime tolerance.', importance: 'Critical' },
      { trait: 'Collaboration & Transparency', description: 'Open-floor culture where engineers collaborate freely with financial analysts.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base; strong presence at Northeast, Big 10, and top engineering schools.',
      minimumGpa: '3.2+ recommended.',
      priorExperiencePreference: 'Previous technical internship or strong systems projects.',
      undergradClassStanding: 'Rising Juniors and Seniors (Penultimate year focus).',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['C++', 'Python', 'JavaScript', 'TypeScript', 'Distributed Systems', 'Real-Time', 'Kafka', 'SQL'],
    redFlags: ['Failing to consider edge cases (null pointers, empty arrays)', 'Poor C++ memory discipline'],
    compensationRange: {
      hourlyRateUsd: '$58.00 - $65.00/hr (~$9,500/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or luxury corporate apartments in Midtown Manhattan',
      relocationBonusUsd: '$1,500 relocation allowance',
      perks: ['Free unlimited gourmet snacks and pantry', 'Terminal access for learning', 'Subsidized transit'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July / August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast (Consistent candidate feedback turnaround)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: '45-min live coding on HackerRank CodePair.', durationMinutes: 45 },
      { roundNumber: 2, name: 'Virtual Onsite Round 1 (Technical Coding)', type: 'Virtual Onsite', description: '60-min DSA coding with senior engineers.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite Round 2 (System Design / Coding)', type: 'Virtual Onsite', description: '60-min data structure design and system internals.', durationMinutes: 60 },
      { roundNumber: 4, name: 'HR & Engineering Manager Fit', type: 'Behavioral / Values Fit', description: '30-min conversation on culture and team matching.', durationMinutes: 30 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
