import { CompanyInsight } from '../types';
import { SEEDED_COMPANY_INSIGHTS, VERIFIED_DATA_SOURCES } from './companyInsightsData';
import { ADDITIONAL_COMPANY_INSIGHTS } from './companyInsightsExpansion';

const FURTHER_COMPANY_INSIGHTS: CompanyInsight[] = [
  // ==========================================
  // 8. QUANT & WALL STREET EXPANSION
  // ==========================================
  {
    id: 'comp-deshaw',
    companyName: 'D.E. Shaw & Co.',
    aliases: ['D. E. Shaw', 'DESCO'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Dynamic Programming', 'Graph Theory', 'Data Structures & Algorithms', 'Python / C++ Architecture'],
      focusAreas: 'Clean code abstractions, mathematical precision, algorithmic optimization, and computational problem solving.',
      liveCodingFormat: 'Interactive CoderPad interview with quantitative software engineers.',
      systemDesignExpectation: 'Not tested for interns; pure algorithmic depth.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: '2 algorithmic problems with strict time limits.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Intellectual Rigor & Curiosity', description: 'Academic mindset, deep thinking, and scholarly approach to software.', importance: 'Critical' },
      { trait: 'Collegial Excellence', description: 'Respectful, collaborative exploration of complex computational questions.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top 15 CS & Ivy League; strong mathematics and CS coursework.',
      minimumGpa: '3.6+ expected on transcript review.',
      priorExperiencePreference: 'Prior software engineering internship or research.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters, PhDs.',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['Python', 'C++', 'Algorithms', 'Data Structures', 'Distributed Systems', 'Math', 'SQL'],
    redFlags: ['Suboptimal big-O complexity', 'Inability to formulate recurrence relations'],
    compensationRange: {
      hourlyRateUsd: '$110.00/hr (~$17,500/mo)',
      housingStipendMonthlyUsd: '$3,000/mo housing stipend or luxury corporate Manhattan apartment',
      relocationBonusUsd: '$2,500 relocation stipend',
      perks: ['Gourmet in-office dining', 'Extensive speaker series & workshops', 'Full healthcare benefits'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July',
      typicalCloseDate: 'October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '90-min algorithmic challenge.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen 1', type: 'Technical Phone Screen', description: 'Algorithms and problem solving.', durationMinutes: 45 },
      { roundNumber: 3, name: 'Technical Phone Screen 2', type: 'Technical Phone Screen', description: 'Deep data structure design.', durationMinutes: 45 },
      { roundNumber: 4, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Advanced algorithms and team fit.', durationMinutes: 135 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-morgan-stanley',
    companyName: 'Morgan Stanley',
    aliases: ['MS', 'Morgan Stanley Technology'],
    tier: 'Top Finance / Wall St',
    industry: 'Investment Banking / Finance',
    headquarters: 'New York, NY / Alpharetta, GA / Baltimore, MD',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['Java / C++ Algorithms', 'Data Structures', 'SQL & Database Optimization', 'Object-Oriented Design'],
      focusAreas: 'Clean Java/C++, enterprise design patterns, relational database optimization, and clear communication.',
      liveCodingFormat: 'HireVue video followed by live technical interview with VP/ED engineers.',
      systemDesignExpectation: 'Basic database schema normalization and REST architecture.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: '2 algorithmic coding challenges + CS concepts.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Do the Right Thing', description: 'Uncompromising integrity, risk awareness, and client excellence.', importance: 'Critical' },
      { trait: 'Lead with Exceptional Ideas', description: 'Continuous innovation in global financial technology.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Core recruiting universities & Top CS programs nationwide.',
      minimumGpa: '3.3+ strictly screened on resume submission.',
      priorExperiencePreference: 'Prior software or finance technology internship.',
      undergradClassStanding: 'Rising Juniors (Summer Technology Analyst program is strictly for penultimate year students).',
      internationalVisaOpenness: 'Moderate (Sponsors CPT, OPT; select visa sponsorship).',
      githubOpenSourceWeight: 'Moderate.',
    },
    resumeHotkeys: ['Java', 'Spring Boot', 'C++', 'Python', 'SQL', 'PostgreSQL', 'Microservices', 'REST APIs', 'Cloud'],
    redFlags: ['GPA below 3.3', 'Inability to write clean object-oriented code'],
    compensationRange: {
      hourlyRateUsd: '$48.00 - $55.00/hr (~$8,000/mo)',
      housingStipendMonthlyUsd: '$2,000/mo housing stipend or relocation package',
      relocationBonusUsd: '$1,000 relocation stipend',
      perks: ['Modern corporate campus facilities', 'Executive mentorship sessions', 'Global technology network'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July 1st',
      typicalCloseDate: 'October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast initial HackerRank distribution',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '90-min coding challenges.', durationMinutes: 90 },
      { roundNumber: 2, name: 'HireVue Video Assessment', type: 'Behavioral / Values Fit', description: 'Video behavioral responses.', durationMinutes: 30 },
      { roundNumber: 3, name: 'Superday (2-3 Rounds)', type: 'Virtual Onsite', description: 'Live coding + system/database design + team fit.', durationMinutes: 120 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-coinbase',
    companyName: 'Coinbase',
    aliases: ['Coinbase Global', 'COIN'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'Remote-First / San Francisco, CA / New York, NY',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Go / Node.js Microservices', 'Distributed Transactions & Consensus', 'Cryptographic Primitives', 'Rate Limiting & Caching'],
      focusAreas: 'Robust Go backend microservices, blockchain node integration, deterministic transaction processing, and high reliability.',
      liveCodingFormat: 'CoderPad coding + practical backend engineering.',
      systemDesignExpectation: 'Designing a crypto payment gateway or order matching ledger.',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA (830+ score target).',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: true },
    },
    cultureTraits: [
      { trait: 'Clear Communication & Mission Focus', description: 'Commitment to increasing economic freedom in the world with high execution speed.', importance: 'Critical' },
      { trait: 'Continuous Learning & Ownership', description: 'High agency and proactiveness in a remote-first work environment.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base; strong focus on demonstrated backend engineering depth.',
      minimumGpa: 'No GPA cutoff.',
      priorExperiencePreference: 'High preference for candidates who have built scalable APIs, distributed backends, or crypto/fintech projects.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, remote contracts).',
      githubOpenSourceWeight: 'High (Go, Rust, Web3/Ethereum smart contract, or backend tooling).',
    },
    resumeHotkeys: ['Go', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'AWS', 'Distributed Systems', 'Cryptography', 'Redis'],
    redFlags: ['Lack of testing in code submissions', 'Unfamiliarity with basic REST/gRPC conventions'],
    compensationRange: {
      hourlyRateUsd: '$60.00 - $68.00/hr (~$10,000/mo)',
      housingStipendMonthlyUsd: '$2,000/mo remote stipend',
      relocationBonusUsd: '$1,000 home office setup bonus',
      perks: ['Complete remote workstation setup (MacBook Pro + 4K monitor)', 'Wellness reimbursement', 'Full benefits'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min algorithmic challenge.', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding on CoderPad + backend systems.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Coding + backend architecture + Coinbase culture memo.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.CODESIGNAL_GCA, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-scale-ai',
    companyName: 'Scale AI',
    aliases: ['Scale', 'Scale.com'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Applied AI & Foundation Models',
    headquarters: 'San Francisco, CA / New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Python / TypeScript Full-Stack Systems', 'Data Pipelines & Distributed Task Queues', 'Fast Heuristics & Geometry', 'Real-time Annotations'],
      focusAreas: 'Speed of shipping, full-stack product velocity, complex data model transformations, and scalable AI evaluation pipelines.',
      liveCodingFormat: 'CoderPad coding + practical software engineering challenge with Scale engineers.',
      systemDesignExpectation: 'Designing an asynchronous task orchestration and human-in-the-loop validation engine.',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA (835+ score target) or practical take-home challenge.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: true },
    },
    cultureTraits: [
      { trait: 'Founder Mentality & Speed', description: 'Relentless work ethic, moving fast, and taking extreme ownership of end-to-end features.', importance: 'Critical' },
      { trait: 'First-Principles Pragmatism', description: 'Choosing the fastest, most effective engineering solution to solve data bottlenecks.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'MIT, Stanford, Waterloo, Berkeley, CMU, Harvard heavily represented.',
      minimumGpa: 'No strict GPA cutoff; problem-solving velocity and past shipped projects prioritized.',
      priorExperiencePreference: 'High preference for previous Tier-1 tech internship or high-growth startup experience.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Extremely high (Full-stack web apps, ML pipelines, developer tools).',
    },
    resumeHotkeys: ['TypeScript', 'Python', 'React', 'Next.js', 'Node.js', 'PostgreSQL', 'Redis', 'Docker', 'PyTorch'],
    redFlags: ['Slow coding speed', 'Inability to connect frontend UI with robust backend schemas'],
    compensationRange: {
      hourlyRateUsd: '$65.00 - $75.00/hr (~$11,000/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments in San Francisco',
      relocationBonusUsd: '$2,000 relocation stipend',
      perks: ['Gourmet in-office dining (Breakfast, Lunch, Dinner)', 'State-of-the-art developer gear', 'Full health coverage'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min algorithmic challenge.', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding + full-stack architecture.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Live coding + system design + founder speed & culture fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.CODESIGNAL_GCA, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-ramp',
    companyName: 'Ramp',
    aliases: ['Ramp Financial'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'New York, NY / Remote',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Python / TypeScript Systems', 'Financial Ledger Transactions', 'Rate Limiters & Locks', 'Complex State Management'],
      focusAreas: 'Clean, robust software architecture, idempotent API design, financial ledger precision, and high product velocity.',
      liveCodingFormat: 'CoderPad live coding in candidate’s language of choice.',
      systemDesignExpectation: 'Designing an expense approval workflow or real-time card authorization engine.',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA (840+ score target).',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: true },
    },
    cultureTraits: [
      { trait: 'Velocity & High Talent Density', description: 'Speed of shipping and building with elite engineering peers.', importance: 'Critical' },
      { trait: 'Customer Impact & Frugality', description: 'Building software that saves companies time and money.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Waterloo, Stanford, MIT, Berkeley, CMU, Ivy+ heavily represented.',
      minimumGpa: 'No strict GPA cutoff; exceptional code quality and speed prioritized.',
      priorExperiencePreference: 'High preference for prior Tier-1 tech internship.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'High.',
    },
    resumeHotkeys: ['Python', 'TypeScript', 'React', 'PostgreSQL', 'FastAPI', 'AWS', 'Docker', 'Idempotency', 'Distributed Systems'],
    redFlags: ['Writing sloppy or unmaintainable code', 'Ignoring edge cases in concurrency'],
    compensationRange: {
      hourlyRateUsd: '$65.00 - $75.00/hr (~$11,000/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments in NYC',
      relocationBonusUsd: '$2,000 relocation stipend',
      perks: ['Catered gourmet meals in NYC office', 'Latest MacBook Pro M3 Max setup', 'Full wellness coverage'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min algorithmic challenge.', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding on CoderPad.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Algorithmic coding + API design + cultural values.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.CODESIGNAL_GCA, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-plaid',
    companyName: 'Plaid',
    aliases: ['Plaid Inc.'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'San Francisco, CA / New York, NY',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Go / TypeScript Core Systems', 'Banking Protocol Parsing', 'Distributed Caching', 'Microservices & gRPC'],
      focusAreas: 'Clean API abstractions, resilient banking integration, distributed queues, and bulletproof security.',
      liveCodingFormat: 'CoderPad coding with senior backend infrastructure engineers.',
      systemDesignExpectation: 'Designing an account aggregation sync worker or webhook delivery system.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 75,
      cutoffScoreDescription: '2 algorithmic coding challenges with focus on data structure design and string/graph algorithms.',
      proctoring: { webcamRequired: false, screenRecording: false, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Principled Pragmatism', description: 'Building the foundational financial plumbing of the internet with high trust.', importance: 'Critical' },
      { trait: 'Impact & Craft', description: 'High standards for documentation, clean API contracts, and team mentorship.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS universities nationwide.',
      minimumGpa: '3.3+ recommended.',
      priorExperiencePreference: 'High preference for strong backend or API infrastructure experience.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['Go', 'TypeScript', 'Node.js', 'PostgreSQL', 'Kafka', 'AWS', 'Microservices', 'REST APIs', 'gRPC'],
    redFlags: ['Poor security practices (e.g. logging credentials)', 'Ignoring distributed retry mechanisms'],
    compensationRange: {
      hourlyRateUsd: '$60.00 - $68.00/hr (~$10,000/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate housing',
      relocationBonusUsd: '$1,500 relocation allowance',
      perks: ['Gourmet in-office lunches', 'Wellness and commuting subsidies', 'Comprehensive health plans'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '75-min coding assessment.', durationMinutes: 75 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding on CoderPad.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Coding + backend architecture + Plaid operating principles.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-cisco',
    companyName: 'Cisco',
    aliases: ['Cisco Systems', 'CSCO', 'Meraki', 'Splunk'],
    tier: 'Tier 2 Elite Tech',
    industry: 'Security & Systems',
    headquarters: 'San Jose, CA / Research Triangle Park, NC / San Francisco, CA (Meraki)',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['Networking Fundamentals (OSI / TCP/IP)', 'C / C++ / Python Systems', 'Tree & Graph Algorithms', 'Multithreading'],
      focusAreas: 'Network protocols, socket programming, packet routing, security access control, and clean object-oriented architecture.',
      liveCodingFormat: 'Webex live coding with senior network and cloud engineers.',
      systemDesignExpectation: 'Basic network topology design and distributed logging.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: '2 coding challenges + networking/OS concepts MCQs.',
      proctoring: { webcamRequired: false, screenRecording: false, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Connecting Everything & Security', description: 'Connecting people securely with world-class networking hardware and cloud software.', importance: 'Critical' },
      { trait: 'Inclusive Collaboration', description: 'High emphasis on team learning, mentorship, and community engagement.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base across all accredited university partners.',
      minimumGpa: '3.0+ recommended.',
      priorExperiencePreference: 'Coursework or projects in Computer Networks, Operating Systems, or Cloud Services.',
      undergradClassStanding: 'Rising Sophomores, Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate.',
    },
    resumeHotkeys: ['C', 'C++', 'Python', 'Networking', 'TCP/IP', 'Linux', 'Sockets', 'Docker', 'Kubernetes'],
    redFlags: ['Zero understanding of TCP vs UDP or OSI model', 'Poor error handling in socket connections'],
    compensationRange: {
      hourlyRateUsd: '$45.00 - $52.00/hr (~$7,500/mo)',
      housingStipendMonthlyUsd: '$2,000/mo housing stipend or corporate apartments',
      relocationBonusUsd: '$1,000 relocation stipend',
      perks: ['Full access to Cisco Silicon Valley amenities', 'Meraki hardware kits', 'Mentorship programs'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'February (Multiple seasonal cohorts)',
      rollingBasis: true,
      urgencyRating: 'STANDARD_FALL',
      recruiterVelocity: 'Moderate',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank Assessment', type: 'OA', description: '90-min coding and networking concepts test.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding + networking/OS fundamentals.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Final Virtual Round (2 Rounds)', type: 'Virtual Onsite', description: 'Systems coding + team cultural values.', durationMinutes: 90 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MASTER_COMPANY_INSIGHTS: CompanyInsight[] = [
  ...SEEDED_COMPANY_INSIGHTS,
  ...ADDITIONAL_COMPANY_INSIGHTS,
  ...FURTHER_COMPANY_INSIGHTS,
];

export const TOTAL_SEEDED_COMPANIES_COUNT = MASTER_COMPANY_INSIGHTS.length;
