import { CompanyInsight } from '../types';
import { VERIFIED_DATA_SOURCES } from './companyInsightsData';

export const ADDITIONAL_COMPANY_INSIGHTS: CompanyInsight[] = [
  // ==========================================
  // 5. QUANT & HIGH FREQUENCY TRADING (EXPANSION)
  // ==========================================
  {
    id: 'comp-jump-trading',
    companyName: 'Jump Trading',
    aliases: ['Jump Trading Group', 'Jump Crypto'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'Chicago, IL / New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['C++20 Templates', 'Cache Locality & SIMD', 'OS & Kernel Bypass', 'Lock-Free Queues', 'Graph Theory'],
      focusAreas: 'Nanosecond-level performance, C++ template metaprogramming, assembly inspection, socket programming.',
      liveCodingFormat: 'CoderPad coding with senior quantitative technologists.',
      systemDesignExpectation: 'Ultra-low-latency market gateway architecture.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: '2 algorithmic problems + deep C++ systems questions. 100% test cases required.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Competitive Excellence', description: 'Obsession with low-latency algorithmic trading edge.', importance: 'Critical' },
      { trait: 'Collaborative Problem Solving', description: 'Iterating rapidly across hardware (FPGA), systems, and algorithmic trading teams.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top Engineering & CS Schools (Illinois, CMU, MIT, Stanford, Michigan, Purdue).',
      minimumGpa: '3.6+ expected.',
      priorExperiencePreference: 'Prior systems programming or HFT/Quant internship.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters, PhDs.',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'Extremely high (C++, Rust, Linux kernel, FPGA/Verilog).',
    },
    resumeHotkeys: ['C++20', 'Low-Latency', 'FPGA', 'Linux Kernel', 'Sockets', 'Lock-Free', 'Concurrency'],
    redFlags: ['Surface level Python only for systems roles', 'Lack of pointer and memory layout intuition'],
    compensationRange: {
      hourlyRateUsd: '$120.00/hr (~$19,200/mo)',
      housingStipendMonthlyUsd: '$3,500/mo housing stipend or luxury corporate housing',
      relocationBonusUsd: '$3,000 lump sum',
      perks: ['Gourmet in-office dining', 'Top-tier tech setup', 'Full benefits package'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July',
      typicalCloseDate: 'September/October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '90-min C++ and DSA challenge.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'C++ low-level systems & DSA.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3-4 Rounds)', type: 'Virtual Onsite', description: 'Systems, algorithms, and cultural fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-optiver',
    companyName: 'Optiver',
    aliases: ['Optiver Trading'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'Chicago, IL / Amsterdam / Austin, TX',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['C++ Systems Programming', 'Concurrency & Locks', 'Object-Oriented Design', 'Algorithmic Optimization'],
      focusAreas: 'Clean C++ object-oriented architecture, thread safety, memory efficiency, and real-time market simulation.',
      liveCodingFormat: 'CoderPad coding + interactive design with trading systems engineers.',
      systemDesignExpectation: 'Designing an order matching engine or message dispatcher.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 120,
      cutoffScoreDescription: 'HackerRank OA consisting of 1 algorithmic challenge + 1 practical object-oriented architecture simulation.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Passion for Markets & Trading', description: 'Curiosity about how financial derivatives and market making work.', importance: 'High' },
      { trait: 'Pragmatic Engineering', description: 'Focus on high-speed reliable execution over theoretical complexity.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS & Engineering universities; strong representation from Big 10 and Ivy+.',
      minimumGpa: '3.4+ recommended.',
      priorExperiencePreference: 'Strong C++ or Java projects with real-time requirements.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors visas globally).',
      githubOpenSourceWeight: 'High for C++ systems.',
    },
    resumeHotkeys: ['C++', 'Multithreading', 'Memory Management', 'Data Structures', 'Linux', 'TCP/IP', 'Design Patterns'],
    redFlags: ['Inability to explain race conditions or mutexes', 'Unclean code architecture'],
    compensationRange: {
      hourlyRateUsd: '$115.00/hr (~$18,400/mo)',
      housingStipendMonthlyUsd: '$3,000/mo housing stipend or corporate apartments',
      relocationBonusUsd: '$2,500 relocation bonus',
      perks: ['Free in-house breakfast, lunch, and snacks', 'Annual intern boat cruise', 'Full 401k match'],
    },
    applicationTimeline: {
      typicalOpenDate: 'Late June / Early July',
      typicalCloseDate: 'October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank Simulation OA', type: 'OA', description: '120-min practical simulation and algorithms test.', durationMinutes: 120 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'C++ object-oriented design and concurrency.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Architecture, DSA, and team fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-five-rings',
    companyName: 'Five Rings',
    aliases: ['Five Rings Capital'],
    tier: 'Tier 1 Quant/HFT',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'New York, NY',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Algorithmic Efficiency', 'Recursion & Dynamic Programming', 'Math & Puzzles', 'C++ & Python Internals'],
      focusAreas: 'Ultra-pure problem solving, math intuition, and algorithmic optimization under strict constraints.',
      liveCodingFormat: 'Interactive live whiteboard and CoderPad with trading technologists.',
      systemDesignExpectation: 'Not tested for interns; algorithmic mastery is prioritized.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: '2 algorithmic problems with strict time and memory limits.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Pure Intellectual Curiosity', description: 'Passion for math puzzles, combinatorial games, and algorithmic beauty.', importance: 'Critical' },
      { trait: 'Direct Communication', description: 'Crisp, articulate technical explanations.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'MIT, Stanford, Harvard, Princeton, Columbia, CMU, Berkeley, Waterloo priority.',
      minimumGpa: '3.7+ expected.',
      priorExperiencePreference: 'Competition math (Putnam/USAMO) or competitive programming (ICPC/Codeforces).',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High.',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['C++', 'Algorithms', 'Putnam', 'ICPC', 'Competitive Programming', 'Math', 'Probability', 'Python'],
    redFlags: ['Slow time complexity', 'Inability to write optimal dynamic programming state transitions'],
    compensationRange: {
      hourlyRateUsd: '$120.00/hr (~$19,200/mo)',
      housingStipendMonthlyUsd: 'Full luxury corporate housing provided in Manhattan',
      relocationBonusUsd: '$3,000 relocation stipend',
      perks: ['Gourmet chef catered dining', 'Exclusive company social events', 'Full health coverage'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July',
      typicalCloseDate: 'October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '90-min algorithmic challenge.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen 1', type: 'Technical Phone Screen', description: 'Math puzzles and algorithms.', durationMinutes: 45 },
      { roundNumber: 3, name: 'Technical Phone Screen 2', type: 'Technical Phone Screen', description: 'Advanced dynamic programming and data structures.', durationMinutes: 45 },
      { roundNumber: 4, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Deep technical problem solving with partners.', durationMinutes: 135 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // 6. BIG TECH & FOUNDATIONAL PLATFORMS (EXPANSION)
  // ==========================================
  {
    id: 'comp-nvidia',
    companyName: 'NVIDIA',
    aliases: ['NVIDIA Corporation', 'NVDA'],
    tier: 'Tier 1 Big Tech / FAANG+',
    industry: 'Cloud / AI / Big Tech',
    headquarters: 'Santa Clara, CA / Austin, TX / Redmond, WA',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['C/C++ Systems & Memory', 'CUDA & GPU Architecture', 'Computer Architecture / OS', 'Data Structures & Pointers'],
      focusAreas: 'Hardware/software co-design, GPU threads, memory bandwidth, SIMD execution, driver development, PyTorch deep learning acceleration.',
      liveCodingFormat: 'Microsoft Teams / HackerRank live coding with specialized GPU kernel and driver engineers.',
      systemDesignExpectation: 'Understanding of GPU interconnects, PCIe bus, memory caching, and parallel computing.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: 'HackerRank test tailored to the specific sub-team (e.g. AI / Deep Learning, GPU Architecture, or Systems Software).',
      proctoring: { webcamRequired: false, screenRecording: false, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'First-Principles Engineering', description: 'Understanding physical constraints, speed-of-light performance, and silicon limits.', importance: 'Critical' },
      { trait: 'Speed & Agility', description: 'Rapid iteration in training models, refining drivers, and scaling supercomputing clusters.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top engineering & computer systems universities (Stanford, Berkeley, UIUC, CMU, Georgia Tech, Purdue).',
      minimumGpa: '3.4+ recommended.',
      priorExperiencePreference: 'High preference for candidates with CUDA, computer graphics (OpenGL/Vulkan), or low-level systems coursework.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters, PhDs.',
      internationalVisaOpenness: 'High (Full visa sponsorship for STEM students).',
      githubOpenSourceWeight: 'Extremely high for CUDA kernels, graphics shaders, or compiler backends.',
    },
    resumeHotkeys: ['CUDA', 'C++', 'GPU Architecture', 'PyTorch', 'Parallel Computing', 'Computer Architecture', 'Linux Kernel', 'C'],
    redFlags: ['No understanding of GPU memory hierarchy (Shared Memory vs Global Memory)', 'Pure web frontend only without systems background'],
    compensationRange: {
      hourlyRateUsd: '$55.00 - $65.00/hr (~$9,500/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments in Silicon Valley',
      relocationBonusUsd: '$1,500 relocation allowance',
      perks: ['Silicon Valley campus amenities', 'NVIDIA GPU hardware perks', 'Direct exposure to AI supercomputer infrastructure'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'January (Ongoing rolling requisitions)',
      rollingBasis: true,
      urgencyRating: 'STANDARD_FALL',
      recruiterVelocity: 'Moderate (Individual team-by-team requisition matching)',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Technical Screening OA', type: 'OA', description: '90-min C++ / Algorithms / Computer Architecture test.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Deep dive into C++, pointer mechanics, and parallel processing.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'GPU programming, algorithms, and team architectural review.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-netflix',
    companyName: 'Netflix',
    aliases: ['Netflix Inc.'],
    tier: 'Tier 1 Big Tech / FAANG+',
    industry: 'Cloud / AI / Big Tech',
    headquarters: 'Los Gatos, CA / Los Angeles, CA / Remote',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Distributed Systems', 'Java / Spring Boot Internals', 'Concurrency & Caching', 'Data Pipelines & Kafka'],
      focusAreas: 'Real-world backend reliability, microservice isolation, chaos engineering, high-throughput streaming systems.',
      liveCodingFormat: 'CoderPad coding + practical systems design with senior engineering staff.',
      systemDesignExpectation: 'High for an internship (focuses on resiliency, caching strategies, and telemetry).',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA (830+ score target).',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: true },
    },
    cultureTraits: [
      { trait: 'Freedom & Responsibility', description: 'Extreme autonomy, mature judgment, and candid feedback.', importance: 'Critical' },
      { trait: 'Stunning Colleagues', description: 'Collaborating effectively with seasoned industry leaders.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base; heavy focus on prior production internship experience.',
      minimumGpa: 'No GPA cutoff (Netflix does not ask for GPA).',
      priorExperiencePreference: 'High preference for candidates with prior Tier-1 tech internship or exceptional production experience.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters (Select summer internship cohort).',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'High for distributed backend, microservice tooling, or open-source libraries.',
    },
    resumeHotkeys: ['Java', 'Distributed Systems', 'Microservices', 'Kafka', 'AWS', 'Spring Boot', 'gRPC', 'GraphQL', 'Redis'],
    redFlags: ['Requiring micromanagement or spoon-feeding in ambiguous scenarios', 'Lack of production systems awareness'],
    compensationRange: {
      hourlyRateUsd: '$65.00 - $75.00/hr (~$11,000/mo)',
      housingStipendMonthlyUsd: '$3,000/mo housing stipend or corporate apartments in Los Gatos',
      relocationBonusUsd: '$2,000 relocation stipend',
      perks: ['Free Netflix premium subscription', 'Top-tier tech setup', 'Full catered meals on campus'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min algorithmic challenge.', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding + backend systems architecture.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds: Coding + System Design + Culture Memo)', type: 'Virtual Onsite', description: 'Technical depth and Freedom & Responsibility cultural alignment.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.ENGINEERING_BLOGS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.LEETCODE_DEBRIEFS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // 7. HIGH-GROWTH UNICORNS & PRODUCT LEADERS (EXPANSION)
  // ==========================================
  {
    id: 'comp-snowflake',
    companyName: 'Snowflake',
    aliases: ['Snowflake Inc.'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'Bozeman, MT / San Mateo, CA / Bellevue, WA',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['C++ & Java Core Systems', 'SQL Query Compilers', 'Distributed Storage & Raft', 'Concurrency & Mutexes'],
      focusAreas: 'Database engine internals, query execution pipelines, vectorized processing, distributed consensus, and cloud storage optimization.',
      liveCodingFormat: 'CoderPad coding with senior database engineers.',
      systemDesignExpectation: 'Basic database index structures (B+ Trees, LSM Trees) and caching layers.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: '2 LeetCode Medium/Hard algorithmic challenges + concurrency concepts.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Put Customers First', description: 'Obsession with query performance and zero data corruption.', importance: 'Critical' },
      { trait: 'Integrity Always', description: 'Rigorous engineering standards and data privacy compliance.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS programs (CMU, Stanford, Berkeley, Waterloo, Washington, Wisconsin-Madison database labs).',
      minimumGpa: '3.4+ recommended.',
      priorExperiencePreference: 'Systems or cloud backend software internship.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters, PhDs.',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'High for storage engines, compilers, or distributed consensus projects.',
    },
    resumeHotkeys: ['C++', 'Java', 'Distributed Systems', 'Database Internals', 'SQL Engine', 'Concurrency', 'Cloud Storage', 'Rust'],
    redFlags: ['No knowledge of ACID properties or basic indexing structures', 'Inability to write thread-safe data structures'],
    compensationRange: {
      hourlyRateUsd: '$62.00 - $70.00/hr (~$10,500/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments',
      relocationBonusUsd: '$2,000 relocation stipend',
      perks: ['Full catered meals', 'Developer hardware setup (M3 Max MacBook Pro)', 'Wellness reimbursement'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '90-min algorithms and data structures assessment.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding + C++/Java systems fundamentals.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Distributed systems, algorithms, and team fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-anthropic',
    companyName: 'Anthropic',
    aliases: ['Anthropic PBC', 'Claude AI'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Applied AI & Foundation Models',
    headquarters: 'San Francisco, CA',
    dsaBar: {
      difficulty: 'Hard',
      primaryTopics: ['Python / PyTorch Systems', 'Distributed Training Protocols', 'Model Evaluation & Alignment', 'High-Throughput APIs'],
      focusAreas: 'AI alignment algorithms, scalable inference serving, token streaming, mechanistic interpretability, and robust Python code.',
      liveCodingFormat: 'Practical live engineering session using realistic ML infrastructure scenarios.',
      systemDesignExpectation: 'High: Scalable inference serving, KV cache optimization, safety guardrail latency.',
    },
    oaType: {
      platform: 'Custom Proctored Platform',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: 'Practical Python / ML systems take-home or algorithmic challenge.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: false, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'AI Safety & Constitutional AI', description: 'Deep intellectual commitment to aligning frontier models with human values.', importance: 'Critical' },
      { trait: 'Scientific Rigor & Transparency', description: 'Documenting empirical findings and reproducing experimental results.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS and AI institutions (Stanford, MIT, Berkeley, CMU, Harvard, Oxford).',
      minimumGpa: 'Not strictly checked; focus on research track record or exceptional systems engineering.',
      priorExperiencePreference: 'Prior experience at top AI lab or high-scale backend infrastructure company.',
      undergradClassStanding: 'Undergraduates with exceptional technical depth, Masters, and PhD students.',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'Extremely high (Transformer models, LLM evaluations, inference pipelines).',
    },
    resumeHotkeys: ['Python', 'PyTorch', 'Distributed Systems', 'Transformers', 'Inference', 'AI Safety', 'CUDA', 'FastAPI'],
    redFlags: ['Treating AI models as black boxes without understanding architectural trade-offs', 'Lack of practical debugging skills'],
    compensationRange: {
      hourlyRateUsd: '$75.00 - $90.00/hr (~$13,500/mo)',
      housingStipendMonthlyUsd: '$3,000/mo housing stipend in San Francisco',
      relocationBonusUsd: '$3,000 relocation stipend',
      perks: ['Gourmet in-office dining', 'Access to cutting-edge Claude foundation model clusters', 'Comprehensive benefits'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'October/November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'Technical Take-Home Challenge', type: 'OA', description: 'Practical AI systems / algorithmic challenge.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Algorithmic problem solving and systems reasoning.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3-4 Rounds)', type: 'Virtual Onsite', description: 'ML systems, live coding, and AI safety mission fit.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.ENGINEERING_BLOGS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-figma',
    companyName: 'Figma',
    aliases: ['Figma Inc.'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Consumer / Social / Design',
    headquarters: 'San Francisco, CA / New York, NY',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['WebAssembly / C++ in Browser', 'Canvas Rendering & WebGL', 'Operational Transformation & CRDTs', 'TypeScript Internals'],
      focusAreas: 'Real-time collaborative multiplayer sync, 60fps canvas rendering, C++ WebAssembly engine, and polished frontend state management.',
      liveCodingFormat: 'CoderPad coding + collaborative web systems building.',
      systemDesignExpectation: 'Multiplayer collaborative canvas architecture (conflict resolution, state synchronization).',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA (830+ score target).',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: true },
    },
    cultureTraits: [
      { trait: 'Design & Craftsmanship Obsession', description: 'Deep appreciation for delightful UX, buttery smooth animations, and precision.', importance: 'Critical' },
      { trait: 'Community Empathy', description: 'Building tools that empower creators and design teams worldwide.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Strong representation from Waterloo, Stanford, Berkeley, Brown, and prominent open-source creators.',
      minimumGpa: 'No GPA cutoff (focus strictly on portfolio, code quality, and technical depth).',
      priorExperiencePreference: 'High preference for candidates who have built complex web applications, WebGL/Canvas tools, or compilers.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Full visa sponsorship).',
      githubOpenSourceWeight: 'Extremely high (Complex frontend architecture, WebAssembly, or canvas libraries).',
    },
    resumeHotkeys: ['TypeScript', 'WebAssembly', 'C++', 'WebGL', 'Canvas', 'CRDTs', 'React', 'Multiplayer', 'State Management'],
    redFlags: ['Generic CSS to-do apps', 'Inability to explain how browser rendering pipeline works (paint, reflow, compositing)'],
    compensationRange: {
      hourlyRateUsd: '$65.00 - $72.00/hr (~$11,000/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments in San Francisco',
      relocationBonusUsd: '$2,000 relocation stipend',
      perks: ['Gourmet in-office dining', 'Design perks & hardware allowance', 'Full wellness coverage'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min algorithmic assessment.', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding + frontend/systems architecture.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds: Coding + Multiplayer Architecture + Values)', type: 'Virtual Onsite', description: 'Technical depth and design alignment.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.ENGINEERING_BLOGS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.CODESIGNAL_GCA],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-robinhood',
    companyName: 'Robinhood',
    aliases: ['Robinhood Markets', 'HOOD'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Fintech / Quantitative Trading',
    headquarters: 'Menlo Park, CA / New York, NY / Remote',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Python / Go Concurrency', 'Financial Ledger Transactions', 'Rate Limiting & Caching', 'Database Sharding & Locks'],
      focusAreas: 'Strict financial transaction idempotency, double-entry bookkeeping ledgers, Kafka streaming, and robust API design.',
      liveCodingFormat: 'CoderPad live coding with backend engineers.',
      systemDesignExpectation: 'Designing an idempotent stock order placement service or price tick stream.',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA (835+ score target).',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: true },
    },
    cultureTraits: [
      { trait: 'Democratize Finance for All', description: 'Commitment to making financial markets accessible and intuitive for retail investors.', importance: 'High' },
      { trait: 'Safety First & Reliability', description: 'Zero tolerance for financial transaction inaccuracies or ledger discrepancies.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting; strong representation across top CS universities.',
      minimumGpa: '3.3+ recommended.',
      priorExperiencePreference: 'High preference for candidates with backend systems or distributed databases experience.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['Python', 'Go', 'Kafka', 'PostgreSQL', 'Distributed Systems', 'Idempotency', 'Redis', 'Docker', 'FastAPI'],
    redFlags: ['Inability to explain ACID transaction guarantees', 'Ignoring database race conditions during concurrent account debits'],
    compensationRange: {
      hourlyRateUsd: '$60.00 - $68.00/hr (~$10,000/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments',
      relocationBonusUsd: '$1,500 relocation allowance',
      perks: ['Home office setup budget ($1,000)', 'Wellness reimbursement', 'Full health coverage'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min algorithmic challenge.', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding on CoderPad + system transactions.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (3 Rounds)', type: 'Virtual Onsite', description: 'Algorithmic coding + Backend API design + Behavioral values.', durationMinutes: 180 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.CODESIGNAL_GCA, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-uber',
    companyName: 'Uber',
    aliases: ['Uber Technologies Inc.'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'San Francisco, CA / Seattle, WA / New York, NY',
    dsaBar: {
      difficulty: 'Medium-Hard',
      primaryTopics: ['Spatial Indexing (H3 / Geospatial)', 'Graph Shortest Path (Dijkstra/A*)', 'Concurrency & Locking', 'Distributed Message Queues'],
      focusAreas: 'Real-time geospatial dispatch, dynamic pricing algorithms, low-latency microservices, and high-throughput Kafka pipelines.',
      liveCodingFormat: 'CoderPad coding with Uber senior distributed systems engineers.',
      systemDesignExpectation: 'Designing location update streams, ride matching, or ETA calculation engines.',
    },
    oaType: {
      platform: 'CodeSignal (GCA)',
      typicalDurationMinutes: 70,
      cutoffScoreDescription: 'CodeSignal GCA (830+ score target).',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: true },
    },
    cultureTraits: [
      { trait: 'Go Get It & Big Bold Bets', description: 'Proactive drive, passion for solving massive physical-world logistics problems.', importance: 'High' },
      { trait: 'Engineering Rigor at Planetary Scale', description: 'Building resilient systems handling millions of concurrent trips worldwide.', importance: 'Critical' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Top CS and Engineering programs across the US and Canada.',
      minimumGpa: '3.2+ recommended.',
      priorExperiencePreference: 'Previous backend or full-stack software development experience.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['Go', 'Java', 'Python', 'Kafka', 'Distributed Systems', 'Geospatial', 'Microservices', 'Redis', 'gRPC'],
    redFlags: ['Failing to account for distributed network partitions', 'Poor algorithmic efficiency on graph search'],
    compensationRange: {
      hourlyRateUsd: '$58.00 - $66.00/hr (~$9,800/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments',
      relocationBonusUsd: '$1,500 relocation stipend',
      perks: ['Uber ride & Uber Eats monthly credits ($500/mo)', 'Full catered campus dining', 'Wellness subsidies'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August',
      typicalCloseDate: 'November',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast',
    },
    interviewStages: [
      { roundNumber: 1, name: 'CodeSignal GCA', type: 'OA', description: '70-min algorithmic assessment.', durationMinutes: 70 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding on CoderPad.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (2-3 Rounds)', type: 'Virtual Onsite', description: 'Coding + systems reasoning + Uber cultural values.', durationMinutes: 135 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.CODESIGNAL_GCA, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-jpmorgan',
    companyName: 'JPMorgan Chase & Co.',
    aliases: ['JPMC', 'J.P. Morgan'],
    tier: 'Top Finance / Wall St',
    industry: 'Investment Banking / Finance',
    headquarters: 'New York, NY / Plano, TX / Jersey City, NJ / Chicago, IL',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['Java Core Fundamentals', 'SQL Queries & Joins', 'Array & String Manipulation', 'Object-Oriented Design'],
      focusAreas: 'Clean Java/Spring Boot code, RESTful API design, database schema normalization, and problem-solving clarity.',
      liveCodingFormat: 'HireVue Coding Assessment followed by Superday live interviews.',
      systemDesignExpectation: 'Basic database schema normalization and microservices communication.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 60,
      cutoffScoreDescription: '2 algorithmic coding challenges on HackerRank (60 min) followed by HireVue video questions.',
      proctoring: { webcamRequired: true, screenRecording: true, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Client Obsession & Operational Excellence', description: 'High reliability in processing $10T+ in global payments daily.', importance: 'Critical' },
      { trait: 'Collaborative Integrity', description: 'High ethical standards, regulatory compliance, and teamwork.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base with dedicated university partnerships nationwide.',
      minimumGpa: '3.2+ strictly screened on resume application.',
      priorExperiencePreference: 'Solid programming coursework and practical class projects.',
      undergradClassStanding: 'Rising Juniors (Summer Software Engineer Program is strictly for penultimate year students).',
      internationalVisaOpenness: 'Moderate (Sponsors CPT, OPT; select full-time visa sponsorship).',
      githubOpenSourceWeight: 'Moderate.',
    },
    resumeHotkeys: ['Java', 'Spring Boot', 'Python', 'SQL', 'REST API', 'AWS', 'React', 'Microservices', 'PostgreSQL'],
    redFlags: ['GPA below 3.2', 'Inability to write standard SQL joins', 'Poor object-oriented structure'],
    compensationRange: {
      hourlyRateUsd: '$48.00 - $55.00/hr (~$8,000/mo)',
      housingStipendMonthlyUsd: '$2,000/mo housing stipend or relocation package',
      relocationBonusUsd: '$1,000 relocation stipend',
      perks: ['Modern corporate campus facilities', 'Executive mentorship sessions', 'Global intern hackathon'],
    },
    applicationTimeline: {
      typicalOpenDate: 'July 1st',
      typicalCloseDate: 'October',
      rollingBasis: true,
      urgencyRating: 'CRITICAL_ROLLING',
      recruiterVelocity: 'Fast initial HackerRank distribution',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '2 coding challenges (60 min).', durationMinutes: 60 },
      { roundNumber: 2, name: 'HireVue Video Assessment', type: 'Behavioral / Values Fit', description: 'Behavioral responses recorded on video.', durationMinutes: 30 },
      { roundNumber: 3, name: 'Superday (2 Technical & Behavioral Rounds)', type: 'Virtual Onsite', description: 'Live coding + system/database design + team fit.', durationMinutes: 90 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI, VERIFIED_DATA_SOURCES.COMMUNITY_SURVEYS],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-salesforce',
    companyName: 'Salesforce',
    aliases: ['Salesforce.com', 'CRM'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Enterprise Infrastructure',
    headquarters: 'San Francisco, CA / Bellevue, WA / Atlanta, GA',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['Java / Python Algorithms', 'Object-Oriented Design', 'Database Queries', 'REST API Architecture'],
      focusAreas: 'Clean code architecture, multitenancy fundamentals, maintainable design patterns, and clear communication.',
      liveCodingFormat: 'HackerRank CodePair live coding with engineering teams.',
      systemDesignExpectation: 'Basic understanding of multitenant databases and cloud architectures.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 90,
      cutoffScoreDescription: '2 algorithmic coding questions + CS core MCQs.',
      proctoring: { webcamRequired: false, screenRecording: false, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Ohana Culture & Trust', description: 'Trust, customer success, innovation, and equality.', importance: 'Critical' },
      { trait: 'Philanthropy & 1-1-1 Model', description: 'Dedication to community giving and positive societal impact.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base across accredited university partners.',
      minimumGpa: '3.0+ recommended.',
      priorExperiencePreference: 'Practical full-stack or backend engineering projects.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters (Futureforce Program).',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate.',
    },
    resumeHotkeys: ['Java', 'Python', 'TypeScript', 'React', 'SQL', 'AWS', 'Microservices', 'REST APIs', 'Docker'],
    redFlags: ['Poor behavioral alignment with Ohana values', 'Overly complex solutions when a simple approach suffices'],
    compensationRange: {
      hourlyRateUsd: '$52.00 - $60.00/hr (~$8,800/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments in San Francisco',
      relocationBonusUsd: '$1,500 relocation allowance',
      perks: ['Salesforce Tower amenities', '1-1-1 volunteer paid time off', 'Wellness reimbursement'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'December',
      rollingBasis: true,
      urgencyRating: 'STANDARD_FALL',
      recruiterVelocity: 'Moderate',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '90-min coding and CS fundamentals challenge.', durationMinutes: 90 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding + object-oriented design.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (2-3 Rounds)', type: 'Virtual Onsite', description: 'Coding + systems discussion + Futureforce Ohana values fit.', durationMinutes: 135 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-adobe',
    companyName: 'Adobe',
    aliases: ['Adobe Inc.', 'ADBE'],
    tier: 'Tier 1 Enterprise Unicorn / High-Growth',
    industry: 'Consumer / Social / Design',
    headquarters: 'San Jose, CA / San Francisco, CA / Seattle, WA / New York, NY',
    dsaBar: {
      difficulty: 'Medium',
      primaryTopics: ['C++ / JavaScript Graphics & DOM', 'Tree & Graph Traversals', 'Arrays & Strings', 'Object-Oriented Design'],
      focusAreas: 'Clean code readability, data structure fundamentals, creative problem solving, and UI/systems integration.',
      liveCodingFormat: 'HackerRank CodePair live coding session.',
      systemDesignExpectation: 'Basic asset caching, image processing pipelines, or cloud document sync.',
    },
    oaType: {
      platform: 'HackerRank',
      typicalDurationMinutes: 75,
      cutoffScoreDescription: '2 algorithmic coding challenges + core CS concepts.',
      proctoring: { webcamRequired: false, screenRecording: false, copyPasteDisabled: true, audioMonitored: false },
    },
    cultureTraits: [
      { trait: 'Creativity for All', description: 'Passion for building tools that unleash human creativity and digital experiences.', importance: 'Critical' },
      { trait: 'Genuine & Exceptional', description: 'Authenticity, high ethical standards, and continuous learning.', importance: 'High' },
    ],
    unspokenFilters: {
      targetSchoolTier: 'Broad recruiting base across all top engineering universities.',
      minimumGpa: '3.0+ recommended.',
      priorExperiencePreference: 'Strong projects in graphics, web applications, or computer vision.',
      undergradClassStanding: 'Rising Juniors, Seniors, Masters, PhDs.',
      internationalVisaOpenness: 'High (Sponsors CPT, OPT, J-1).',
      githubOpenSourceWeight: 'Moderate-High.',
    },
    resumeHotkeys: ['C++', 'JavaScript', 'TypeScript', 'React', 'Computer Graphics', 'Python', 'Algorithms', 'WebAssembly'],
    redFlags: ['Ignoring code readability and modularity', 'Inability to explain basic graph/tree complexities'],
    compensationRange: {
      hourlyRateUsd: '$50.00 - $58.00/hr (~$8,500/mo)',
      housingStipendMonthlyUsd: '$2,500/mo housing stipend or corporate apartments in San Jose/SF',
      relocationBonusUsd: '$1,500 relocation stipend',
      perks: ['Free Creative Cloud all-apps subscription', 'World-class Silicon Valley headquarters amenities', 'Wellness subsidies'],
    },
    applicationTimeline: {
      typicalOpenDate: 'August / September',
      typicalCloseDate: 'December',
      rollingBasis: true,
      urgencyRating: 'STANDARD_FALL',
      recruiterVelocity: 'Moderate',
    },
    interviewStages: [
      { roundNumber: 1, name: 'HackerRank OA', type: 'OA', description: '75-min algorithms assessment.', durationMinutes: 75 },
      { roundNumber: 2, name: 'Technical Phone Screen', type: 'Technical Phone Screen', description: 'Live coding + project deep-dive.', durationMinutes: 60 },
      { roundNumber: 3, name: 'Virtual Onsite (2-3 Rounds)', type: 'Virtual Onsite', description: 'Coding + systems discussion + Adobe creative values.', durationMinutes: 135 },
    ],
    dataSources: [VERIFIED_DATA_SOURCES.SIMPLIFY_PITTS, VERIFIED_DATA_SOURCES.LEVELS_FYI],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
